### ISSUE TITLE
[IHM] - Gestion des DU avec des sites génériques et sites modèles

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1292]
Proposition 1 :
DU composé sur n Sites
-Site 1
--Site 2
--Site 3

Avantage
-Déjà réalisé
-Faisable

Défaut
Multiplication des unités
Certaines unité ne concerne certain site unitaire

Proposition 2 :
UT3 qui est lié à l'unité partagé UT1
Sur l'UT3 on affiche :
-Risque hérité
-Signalisation hérité
-Les évaluateurs

**Comment by lmag** [comment]
Exemple et maquette à faire avec le partage des entités et la possibilité d'affecter une entité à une autre
<img width="713" alt="image" src="https://user-images.githubusercontent.com/3288514/145021627-2534f57e-a252-4fcd-975b-9b73c11f4fda.png">

**Comment by eoxia-amandine** [comment]
Proposition wireframe

**Lier une UT/GP à un enfant :**
![1-liaison](https://user-images.githubusercontent.com/18576747/145072859-ad8bf531-24ec-4dff-a99a-060d62844085.png)

**Listing du tableau des risques de l'enfant :**
![2-listing](https://user-images.githubusercontent.com/18576747/145072873-d3a4dadc-2102-4ece-a2bd-c19ec5a693a7.png)

**Partage sur un site parent**
![3-partage-du-site](https://user-images.githubusercontent.com/18576747/145072879-d70d0173-9ea7-496d-81b5-2e95fa2d05fb.png)

**Comment by lmag** [comment]
Parfait merci

**Comment by evarisk-theo** [comment]
pouvoir lier une UT/ un GP à un GP/UT d'une autre entité (EN V2)
V1 : pouvoir lier un risque provenant d'une GP/UT extérieur partagé

quand on lie, on voit la liste des risques du GP/UT et on sélectionne ceux qu'on veut
 on crée un lien entre chaque risque de l'ut mère et l'ut cible
quand on génère le DU/ la fiche gp ou ut, on récupère les risques du gp/ut et de celui parent 

distinction sur les fiches entre ce qui est hérité et ce qui est propre à l'unité/gp


POUVOIR partager risques, tâches

Ajouter entité devant le nom du GP  dans la liste des risques fiche UT/GP

**Comment by lmag** [comment]
Attention à ne prendre que les risques partagés donc prévoir le partage des risques dans le module multicompany
