### ISSUE TITLE
format xml déclaration

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#1339]

**Comment by evarisk-theo** [comment]
[Exemple_Enveloppe_DAT_V05_07.zip](https://github.com/Evarisk/Digirisk/files/7677822/Exemple_Enveloppe_DAT_V05_07.zip)

**Comment by evarisk-theo** [comment]
[Liste_DAT_V5_1.pdf](https://github.com/Evarisk/Digirisk/files/7677825/Liste_DAT_V5_1.pdf)

**Comment by lmag** [comment]
Ça c est cool
