### ISSUE TITLE
[DU] - Nombre de jours avant prochaine génération du DU

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1540]
-Date du dernier DU
-Date du prochain DU
-Combien de jour avant de le faire
-Combien de jour le délais est dépassé

[#2158](https://github.com/Evarisk/Digirisk/issues/2158)

**Comment by nicolas-eoxia** [comment]
![image](https://user-images.githubusercontent.com/52404047/152379039-ac236998-3ebb-4e8a-956a-a5a9e61c5bc7.png)
