### ISSUE TITLE
[BUG]Déplacement impossible dans l'arborescence

### ISSUE THREAD

**Issue by carolineroussarie** [Evarisk/Digirisk#1556]
**Vous avez trouvé un BUG ! Bravo !*
déplacement impossible dans l'arborescence

**Vous pouvez décrire comment le reproduire ici**
déplacement UT GP non enregistré

**Copie d'écran**
On adore les copies d'écran afin de mieux comprendre

**Votre configuration sauf si vous êtes chez evarisk.com**
dolibarr14.05 et digirisk 9.01

**Smartphone **

**Remarques**

**Comment by lmag** [comment]
Le bug est reproductible sur la démo
