### ISSUE TITLE
[Amélioration] : Nombre de caractères dans les tâches non enregistré

### ISSUE THREAD

**Issue by carolineroussarie** [Evarisk/Digirisk#1583]
contrôler le nombre de caractères et afficher un message si nombre dépassé
![image](https://user-images.githubusercontent.com/75376977/154238686-63e15872-191c-4b98-802c-c065f6ff3aec.png)

**Comment by lmag** [comment]
255 caractères dans les titres des taches mettre un message d'alerte si on dépasse le nombre

**Comment by nicolas-eoxia** [comment]
on juste faire le trunc a 255 caractère
