### ISSUE TITLE
[Amélioration] Sur les tris lors des copier/coller sous libre office

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1585]
**La description de la fonction attendue.**
Conserver un paramètre triable
**La description des données dont vous avez besoin**
Export en listing .csv
Les images sont remplacées par un champ vide on ne peut donc plus trier facilement

<img width="519" alt="image" src="https://user-images.githubusercontent.com/3288514/154254541-785cb5a3-01b3-4e7e-bf93-23e0fbd64363.png">

**Comment by nicolas-eoxia** [comment]
ODT : pour les risques mettre le nom du risques en dessous pour préparer le tris dans un tableur

**Comment by nicolas-eoxia** [comment]
![image](https://user-images.githubusercontent.com/52404047/178039119-7a064d80-5c01-4555-ad45-ce3ed8e1977a.png)
