### ISSUE TITLE
Menus Société : Onglet Sécurité et Social vides

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#1603]
Bonjour,

je viens d'installer la dernière version de Digirisk sur un serveur Ubuntu et Dolibar V14.0.5

Tout s'est passé correctement excepté que j'ai un affichage vide sur les pages Sécurité et Social de Société.

PHP_OS | Linux
Version | Linux ubnt-bh2m-01 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64
Version | Apache/2.4.41 (Ubuntu)
PHP Version | 7.4.3

Merci
Frederic
![Capture d’écran 2022-02-24 101810](https://user-images.githubusercontent.com/100215218/155495254-f2be1766-168b-4e5e-96aa-b17588da0529.jpg)

**Comment by FredBl79** [comment]
Le bug vient de la gauge, solutionné en mettant en commentaire dans les 2 fichiers securityconf.php et socialconf.php 

<?php //include_once '../core/tpl/digiriskdolibarr_configuration_gauge_view.tpl.php'; ?>

**Comment by nicolas-eoxia** [comment]
Bonjour @FredBl79, 

Pouvez-vous aller sur les fichiers de votre serveur.
Normalement vous devriez trouver un ficher appelée error_log qui contient l'erreur php provoqué par la page socialconf.php et securityconf.php

Ce fichier se trouve précisement dans le chemin d'accès suivant : /votreserveur/htdocs/custom/digiriskdolibarr/admin

**Comment by FredBl79** [comment]
Bonjour @nicolas-eoxia 

je n'ai aucun fichier error_log dans ce répertoire. Désolé

**Comment by FredBl79** [comment]
@nicolas-eoxia, j'ai trouvé le root cause, la fonction BCDIV est utilisée dans certaines pages admin et aussi dans les accidents, si la librairie php-bcmath n'est pas installée sur le serveur, cela bloque l'ouverture des pages.

Cordialement
Fred
