### ISSUE TITLE
Etendre permission groupe

### ISSUE THREAD

**Issue by Alexandra-copac** [Evarisk/Digirisk#1605]
![image](https://user-images.githubusercontent.com/60659447/155498095-4f51b72e-b4f3-45fa-af41-3a8a20947e45.png)

Pouvoir étendre les droits sur les autres entités en récursif.

**Comment by nicolas-eoxia** [comment]
Question pour multi company comment affecter un user a group sur chaque entité d'un coup

**Comment by nicolas-eoxia** [comment]
![image](https://user-images.githubusercontent.com/52404047/178042495-ea73feed-def0-4bde-9878-b82928b9fc06.png)
