### ISSUE TITLE
Problème du mot clé Rank utilisé dans DU et réservé sur Mysql 8.0

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#1606]
Bonjour,

J'ai installé Dolibarr sur Ubuntu avec Mysql 8, Digirisk ne peut pas fonctionner car il utilise une colonne RANK dans la table llx_digiriskdolibarr_digiriskelement. Toute tentative de création d'un élément GP ou WU plante directement.

En effet RANK est un mot clé réservé de Mysql 8

J'ai solutionné localement le problème en renommant RANK en RANKS dans la DB et tout le code de Digrisk.

Merci de mettre à jour le package

**Comment by lmag** [comment]
Bonjour,

Merci @FredBl79 et pourquoi pas pousser une petite PR ? Ca serait super ? Sinon on va regarder de notre coté pour la prochaine version de DigiRisk

Merci !

**Comment by FredBl79** [comment]
Bonjour,

Mon premier PR : https://github.com/Evarisk/Digirisk/pull/1607
Désolé si la mise en forme n'est pas correcte....je débute ;)

Bonne journée
Frederic

**Comment by lmag** [comment]
@nicolas-eoxia
