### ISSUE TITLE
[Amélioration] -Utilisation de la fonction MAINAUTO

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1610]
**La description de la fonction attendue.**
![image](https://user-images.githubusercontent.com/3288514/156220041-c58ee100-9f7c-4de8-9ceb-f26619ea3181.png)

**Comment by nicolas-eoxia** [comment]
J'ai fait un petit test de création de nouveaux triggers, cependant jai remarqué que la variable ne pouvait pas récupéré le bon object lié en effet, récupère unique l'objet qui apelle le triggers
ex : pour risk sign on veut le lié a un digirisk element or dans ce cas il va le lié forcement a un risk sign
