### ISSUE TITLE
contrôler l'homogénisation des catégories de risques

### ISSUE THREAD

**Issue by carolineroussarie** [Evarisk/Digirisk#1616]
**La description de la fonction attendue.**
Les risques peuvent être évalués sous une catégorie puis la catégorie peut être changée, comment ça se passe dans les tris?

**Comment by carolineroussarie** [comment]
![image](https://user-images.githubusercontent.com/75376977/157018267-6e99b43f-a685-4fbf-84f1-d43e72a31532.png)

**Comment by lmag** [comment]
- [ ] Analyser les données
- [ ] Proposer une migration du passif dans les catégories disponibles
- [ ] Migrer les données
- [ ] Archiver la migration dans un évènement Dolibarr

**Comment by nicolas-eoxia** [comment]
Cela concerne la gestion des évènement uniquement pour avoir une trace sur la modification effectué
