### ISSUE TITLE
Demande d'ajout de la fonctionnalité d'export des tickets dans les exports standard de Dolibarr

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1642]
Ajout des exports pour les tickets

**Comment by lmag** [comment]
Ajout de l'export des tickets
![image](https://user-images.githubusercontent.com/3288514/159453772-8290c54e-059e-4d55-bdc1-6e8040a736fa.png)

**Comment by lmag** [comment]
En attente des champs demandés @perrine

**Comment by PerrineSICTOM** [comment]
Ref
Date création
Assigné à
Message
Etat
Nom
Prénom
Téléphone
Service
Lieu
Date

mais les autres peuvent servir aussi ;) (le TOOL serait peut-être la solution)

**Comment by lmag** [comment]
Test de la listincsv non fonctionnel
Test export csv non présent dans les export standard

**Comment by lmag** [comment]
Question si on souhaite exporter avec des TAGs comment on gère le nombre de tag et les exports comme 👍 1;2;3;4;5;
Ref;Date création;Assigné à;Message;TAG1;TAG2;TAG3;ETAT
Ref;Date création;Assigné à;Message;TAG1;TAG2;ETAT
Ref;Date création;Assigné à;Message;ETAT

Solution 1 : Tri par TAG
Solution 2 : Export uniquement sur une série de TAG ({TAG1;TAG2;TAG3})

**Comment by lmag** [comment]
La fonction d'export direct dans export est plus simple
