### ISSUE TITLE
[Amélioration]- Fiche récapitulative ticket

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1643]
**La description de la fonction attendue.**
Réaliser une fiche de récap d'un ticket

**La description des données dont vous avez besoin**
Pouvoir imprimer un résumé d'un ticket avec les informations de traçabilité du ticket

**Comment by lmag** [comment]
[template_ticket.odt](https://github.com/Evarisk/Digirisk/files/8323533/template_ticket.odt)

**Comment by lmag** [comment]
Dans la core de Dolibarr il manque les informations pour la génération document
Show_Document

**Comment by PerrineSICTOM** [comment]
Proposition de format pour exportation ticket avec évènements et agenda
[template_ticket.odt](https://github.com/Evarisk/Digirisk/files/8531050/template_ticket.odt)

**Comment by lmag** [comment]
Ajouter les TAGs sur template
