### ISSUE TITLE
Document Unique ODT - Bug des contacts attachés aux tâches

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#1648]
Bonjour,

Lors de la génération du DU en ODT, le chapitre '4	Hiérarchisation des risques et programme annuel de prévention
' contient la liste des risques avec les tâches, avancement et contacts. Il se trouve que les contacts affichés sont incorrect (doublons, manquants, tous les contacts)

A priori le code récupère les bons contacts, mais les arrays intermediaires posent problèmes.

Pour corriger cela : 
digiriskdolibarr/core/modules/digiriskdolibarr/digiriskdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php

line 487 : j'ai retiré le tableau $contact_array et directement initialisé la variable $AllInitiales

```
if (!empty($related_tasks) && is_array($related_tasks)) {
	foreach ($related_tasks as $related_task) {
		$AllInitiales = '';
		$related_task_contact_ids = $related_task->getListContactId();
		if (!empty($related_task_contact_ids) && is_array($related_task_contact_ids)) {
			foreach ($related_task_contact_ids as $related_task_contact_id) {
				$user->fetch($related_task_contact_id);
				*/$contact_array[$related_task_contact_id] = $user;
				$AllInitiales .= strtoupper(str_split($user->firstname, 1)[0]. str_split($user->lastname, 1)[0] . ',');

			}
		}
		/*$AllInitiales = '';
		if (!empty($contact_array) && is_array($contact_array)) {
			foreach ($contact_array as $contact_array_single) {
				$initiales = '';
				if (dol_strlen($contact_array_single->firstname)) {
					$initiales .= str_split($contact_array_single->firstname, 1)[0];
				}
				if (dol_strlen($contact_array_single->lastname)) {
					$initiales .= str_split($contact_array_single->lastname, 1)[0];
				}
				$AllInitiales .= strtoupper($initiales) . ',';
			}
		}*/
```

Cela peut poser potentiellement problème si le même user est ajouté 2 fois en contact avec 2 rôles différents mais à minima pour mon DU, j'ai bien que les contacts assignés aux tâches dans le fichier ODT.

Cdlt
Frederic

**Comment by nicolas-eoxia** [comment]
Bonjour Frederic,

Je viens d'implémenter la résolution du problème que vous m'avez fait part en version 9.2.0. 
Merci à vous de participer à l'amélioration du module et à son évolution.

Bonne journée,
Nicolas

**Comment by FredBl79** [comment]
Bonsoir,

De rien, j'ai remarqué que le bug se répète sur tous les documents générés
en ODT utilisant les tâches. Je pense que le même code se répète
ailleurs....

Cordialement
Frédéric

Le jeu. 14 avr. 2022, 20:03, Nicolas Domenech ***@***.***> a
écrit :

**Comment by nicolas-eoxia** [comment]
Bonjour,

Oui, le code est utilisé dans tout les document ODT ou l'affichage et similaire mais je me suis basé sur votre exemple pour régler le problème et le mettant dans tous les documents.

Bonne journée
Nicolas
