### ISSUE TITLE
conf sur chaque entité permettre le partage des risques

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/Digirisk#1655]

**Comment by lmag** [comment]
![image](https://user-images.githubusercontent.com/3288514/160092433-e67283b3-340d-47ac-951c-3d9dc710feab.png)

**Comment by lmag** [comment]
V0 - Hook footer

**Comment by lmag** [comment]
Ticket ouvert réponse ok mise en ligne

![image](https://user-images.githubusercontent.com/3288514/160158547-9462fbcb-d2b9-4865-9722-1f65146fd2f7.png)
