### ISSUE TITLE
[Amélioration] - Manque la personne loggué

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1910]
**La description de la fonction attendue.**
![image](https://user-images.githubusercontent.com/3288514/172612863-5e0b62ea-b25f-4a27-b5d3-bd376f622f99.png)

**Comment by nicolas-eoxia** [comment]
remonté l'auteur de l'évaluation sur la première ligne
EX : RA17 - date - par : Initiale auteur
