### ISSUE TITLE
[Amélioration] on ne voit pas le bouton

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1915]
**La description de la fonction attendue.**
![image](https://user-images.githubusercontent.com/3288514/172627581-ccfbc132-4f1f-41ba-b17c-e4532339e05d.png)

**Comment by nicolas-eoxia** [comment]
remplacer modèle du documement par une icon

**Comment by lmag** [comment]
Icone à gauche: 
<i class="fa-solid fa-file-word"></i>
Icone à droite (au lieu de "générer"
<i class="fa-solid fa-print"></i>
