### ISSUE TITLE
[Amélioration] - Ajout de rôles sur les évaluateurs basé sur Poste/fonction dans Dolibarr

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1928]
378a2d07a5b6d0e7f539ad0d2f837540b406a40f

ec108f627c5aa6eb3fba5fbf4064594ec769b4c3

**Comment by lmag** [comment]
- [ ] Ajout d'un roles
- [ ] Ajout des personnes au sein du GP master avec heritage
- [ ] Ajout des personnes partagés sur les risques génériques

![image](https://user-images.githubusercontent.com/3288514/172806191-3ccde205-57d6-4a5f-a77b-143bf9cbbdbc.png)

**Comment by nicolas-eoxia** [comment]
Quel sont les rôles a ajoutés ?
