### ISSUE TITLE
CSS - Dans l'onglet Sécurité

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#1930]
**Vous avez trouvé un BUG ! Bravo !**
![image](https://user-images.githubusercontent.com/3288514/172856586-83c36e94-c4d0-4bd4-8b90-5571ad573d17.png)

**Comment by nicolas-eoxia** [comment]
Bug lié au fait de load notre JS sur ces pages.
- Si le MinimizeMenu est activé, comme on stock en localstorage
