### ISSUE TITLE
Rapport des actions environnementales par Etablissement

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#1962]
- [ ] Définir le rapport de sorti sur les risques environnementaux

**Comment by 0000N** [comment]
Bonjour, 
ça répond à la demande ? (document en pj).


[Rapport environnement.pdf](https://github.com/Evarisk/Digirisk/files/14167414/Rapport.environnement.pdf)

Cordialement,

**Comment by lmag** [comment]
Voir en plus le fichier excel de suivi @lmag

**Comment by lmag** [comment]
Duplicate : https://github.com/Evarisk/Digirisk/issues/3736
