### ISSUE TITLE
Choisir le type de cartographie/arborescence

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#1964]
- [x] Question la cartographie doit être égale au Document Unique ou pas ?

**Comment by lmag** [comment]
3 choix possibles 

- Arborescence autonome (Tres pratique et pas de limite, séparation des droits facile)
**-> Arborescence du Document Unique (Simple mais un peu limité)** - Solution choisie
- Liaison les 2 arborescences (Plus complexe en liaison, donc plus de travail mais c'est le plus complet)

Choix réunion du 23/02/024
- Arborescence du Document Unique (Simple mais un peu limité) mis en place dans un onglet dédiés à l'analyse de risque

**Comment by lmag** [comment]
15/03/2024 - OK mise en place réunion
