### ISSUE TITLE
Etablir les cotations des risques environnementaux

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#1966]
- [x] Définir la cotation des risques environnement
- [x] Risque Brut vs Risque Net (Actions préventives)
- [x] Faire un choix sur les cotations possibles et la priorité

**Comment by lmag** [comment]
Dans un premier temps baser la cotation sur 

- [x] Échelle de 0 à 100
- [x] Proposer par défaut sur 4 niveaux de couleurs

Etudier une matrice avancée sur la base de l'ISO et par type de risque

https://github.com/Evarisk/Digirisk/issues/3652

Version 2 

- [ ] Proposer une double cotation avec la notion réglementaire (Case à cocher)

**Comment by SecuUrano** [comment]
Concernant la matrice de cotation utilisée en environnement, elle est synthétisée ci-dessous : 
nous partons des domaines attendus via une liste de diffusion ou présentation similaire à celle proposée par le DU : 
- Consommation
- Emissions atmosphériques 
- Effluents liquides
- Elimination de déchets
- Nuisances
- Sol / sous-sol
- Risques

Nous listons les impacts possibles et liés aux domaines précédemment sélectionnés : 
- Consommation d'énergie / diminution de la ressource
- Consommation de matière / diminution de la ressource
- Consommation d'eau / diminution de la ressource 
- Pollution par gaz de combustion / échappement
- Pollution par poussière ou solide pulvérulent
- Pollution par COV
- Pollution par gaz toxique ou nocif 
- Pollution par gaz, vapeur, brouillard, fumées
- Pollution eaux 
- Pollution par fuite, déversement 
- Pollution liée à l'élimination de DIB, OM
- Pollution liée à l'élimination de DIS, déchets souillés
- Pollution liée à l'élimination d'emballage, plastiques et papiers
- Pollution liée à l'élimination de déchets dangereux, DTQD
- Nuisance sonore
- Valorisation, réutilisation
- Impact biodiversité
- Suspicion / détection de déchets amiantés
- Suspicion / détection d'engins de guerre
- Dommage sur ouvrage
- Incendie, explosion

Cotation de la fréquence d'apparition de l'aspect : 1 pour au moins une fois par an/3 pour hebdomadaire, mensuel/5 pour journalier
Cotation de la gravité : 1 pour Négligeable / 2 pour Mineure / 3 pour Modérée / 4 pour Grave / 5 pour Majeure
Cotation de la sensibilité : elle s'évalue en fonction du milieu et du domaine associé à l'aspect, toujours allant de 1 /3 / 5
Concernant la maitrise : nous souhaitons décoter les risques : 
- 0,25 : bonne maitrise
- 0,50 : maitrise partielle
- 0,75 : maitrise insuffisante 
- 1 : aucun moyen de maitrise mis en œuvre 
En complément la conformité réglementaire se cote en lettres : 
- C : conforme
- NC : Non conforme
- ND : non défini
- SOR : sans obligation réglementaire applicable
à partir de là un AES si la multiplication des fréquence, gravité, sensibilité, maitrise est supérieure à 75 ou si la conformité réglementaire et NC ou ND avec plan d'actions obligatoire.

Je vous joins un lien de la méthodologie généralement appliquée pour que vous ayez une idée de l'attendu : 
https://sme.blog4ever.com/analyse-environnementale

**Comment by nicolas-evarisk** [comment]
Voir exemple d'analyse environnementale sur le réseau

**Comment by lmag** [comment]
La proposition de Chat GPT
[Analyse_Risque_Environnemental_Kinney.ods](https://github.com/Evarisk/Digirisk/files/14411203/Analyse_Risque_Environnemental_Kinney.ods)

La méthode de Kinney, aussi connue sous le nom de méthode KLS (Kinney & Wiruth), est une approche semi-quantitative pour l'évaluation des risques. Elle permet de déterminer le niveau de risque en combinant la probabilité d'occurrence d'un événement, la fréquence d'exposition et la gravité des conséquences. Cette méthode peut être adaptée à une analyse du risque environnemental et formalisée dans un fichier ODS (OpenDocument Spreadsheet) pour faciliter son utilisation et sa mise à jour. Voici les étapes pour créer une méthode basée sur la méthode de Kinney et la formaliser dans un fichier ODS :

1. Préparation du fichier ODS
Créez un tableau dans le fichier ODS avec des colonnes pour chaque aspect de l'analyse de risque : Identifiant du risque, Description du risque, Probabilité (P), Fréquence d'exposition (F), Gravité (G), Niveau de Risque (LR), et Actions recommandées.
Définissez les échelles pour la Probabilité (P), la Fréquence (F) et la Gravité (G), généralement de 1 à 4 ou de 1 à 5, où 1 représente le niveau le plus bas et 4 ou 5 le niveau le plus élevé.
2. Identification des risques
Listez tous les risques environnementaux potentiels associés à votre activité ou projet. Cela peut inclure la pollution de l'air, la contamination de l'eau, les déchets dangereux, etc.
3. Évaluation des risques avec la méthode de Kinney
Évaluez la Probabilité (P) de chaque risque identifié sur votre échelle définie.
Déterminez la Fréquence d'exposition (F) à ce risque pour le personnel, l'environnement, ou les deux.
Évaluez la Gravité (G) des conséquences si le risque se réalise.
Calculez le Niveau de Risque (LR) en multipliant ces trois facteurs : 
LR=P×F×G.
4. Analyse des résultats et recommandations
Analysez le niveau de risque obtenu pour chaque risque. Plus le score est élevé, plus le risque est critique.
Déterminez des actions de mitigation appropriées pour les risques avec un niveau élevé et inscrivez-les dans la colonne des Actions recommandées.
5. Mise en forme et automatisation dans le fichier ODS
Utilisez des formules pour automatiser le calcul du Niveau de Risque (LR) dans votre fichier ODS.
Appliquez des couleurs conditionnelles pour visualiser rapidement les niveaux de risque (par exemple, rouge pour élevé, orange pour moyen, et vert pour bas).
Incluez des filtres pour trier ou cacher les risques en fonction de leur niveau, facilitant l'analyse et la priorisation des actions.
6. Conclusion et suivi
Revoyez régulièrement l'analyse des risques pour mettre à jour les scores en fonction des changements dans l'activité ou dans l'environnement.
Assurez un suivi des actions recommandées pour s'assurer qu'elles sont implémentées et qu'elles ont l'effet escompté sur la réduction des risques.
Je vais maintenant créer un exemple de structure de fichier ODS basée sur ces instructions.

L'exemple de structure pour l'analyse du risque environnemental basée sur la méthode de Kinney a été créé et sauvegardé dans un fichier ODS. Vous pouvez télécharger le fichier en utilisant le lien suivant :

Analyse_Risque_Environnemental_Kinney.ods

Ce fichier contient un tableau avec des colonnes pour l'identifiant du risque, la description, la probabilité, la fréquence d'exposition, la gravité, le niveau de risque calculé, et les actions recommandées. Vous pouvez l'ouvrir avec n'importe quel logiciel compatible avec le format ODS pour voir l'exemple et l'adapter à vos besoins spécifiques. ​

**Comment by lmag** [comment]
Proposition de matrice simple


[risques environnementaux.odt](https://github.com/Evarisk/Digirisk/files/14465005/risques.environnementaux.odt)


![Image](https://github.com/Evarisk/Digirisk/assets/3288514/9c3aa0ff-1b07-4fd1-9dfa-de80799025f8)

**Comment by lmag** [comment]
@SecuUrano est ce ok pour vous

**Comment by SecuUrano** [comment]
Bonjour, c'est ok de notre côté, bien que la cotation à 0 ne sera pas utilisée au début car peu pertinente

**Comment by SecuUrano** [comment]
Pouvons-nous ajouter une ligne "réglementaire" à la cotation pour intégrer l'aspect veille directement à la cotation ?

**Comment by baptistehsedynamics** [comment]
Le maintien de la cote à 0 n'est pas pertinent au sans de la cotation des aspect mais cela permet de garder le même  système de cotation que pour le DU donc une certaine homogénéité.
A voir à l'usage si cela n'est pas problématique mais d'après les simulations ce n'est pas le cas.

Pour la ligne règlementaire, la norme traite les obligations de conformité dans le chap 6.1.3 distinct du chapitre 6.1.2 relatif aux aspects.
De fait je ne pense pas que ce soit l'endroit pour traiter la conformité, mais a discuter en fonction des vos problématiques et attentes.

**Comment by SecuUrano** [comment]
Ok pour le 0, par contre l'intégration du réglementaire à l'analyse environnementale nous a été demandée en audit de certification, il doit y avoir un lien entre les aspects identifiés et la conformité de l'organisation à la réglementation avec une priorisation des actions découlant de la veille réglementaire : si nous ne sommes pas conforme cela devient automatiquement un AES

**Comment by lmag** [comment]
Il me semble que nous pourrions traiter Les non-conformités réglementaires dans le natif de dolibarr avec les ticket en faisant une catégorie dédiée.
Ceci, Nous permettrait d'isoler de manière séparée lisible et simple. Je traite déjà les non conformité de la marque NF est c es assez pratique.

**Comment by lmag** [comment]
@nicolas-evarisk

**Comment by SecuUrano** [comment]
d'accord on verra avec la pratique si cela suffit ou si l'on sera obligés de l'intégrer

**Comment by mbadier** [comment]
Proposition d'entête de colonne Excel
Unités	Secteur	Contexte	Aspect environnemental	Description de l'aspect	Impact environnemental	Description de l'impact	Domaine d'impact	Fonctionnement	Sensibilité du milieu récepteur	Fréquence	Gravité	Criticité 1	Description des conditions actuelles de maîtrise	Maîtrise	Criticité 2	Aspect	Niveau d'influence	Pourquoi et comment ?	Mesures de prévention	Description de la mesure	Responsable	Délais

**Comment by SecuUrano** [comment]
Pourquoi autant de colonnes svp ?

**Comment by lmag** [comment]
Proposition de passage à Maitrise : 
- ![image](https://github.com/Evarisk/Digirisk/assets/3288514/2db8f118-d9f3-488f-9a20-e52bfbf09115)

**Comment by lmag** [comment]
Validation réunion du 15/03/2024

**Comment by lmag** [comment]
@mbadier 

A priori avec cette méthode on bien tous les éléments du tableau Excel envoyé

- [x] Unités et Secteur = UT et GP
- [x] Contexte = description du risque
- [x] Aspect environnemental = Catégorie du risque
- [x] Description de l'aspect = Description De l'évaluation

**Méthode de cotation :**

- [x] -Impact environnemental
- [x] -Description de l'impact = Description de l'évaluation
- [x] -Domaine d'impact
- [x] -Fonctionnement
- [x] -Sensibilité du milieu récepteur
- [x] -Fréquence = Cotation
- [x] -Gravité = Cotation

**Plan d'action classique :**
Actions Soldées de maitrise =

- [x] Criticité 1 Description des conditions actuelles de maîtrise Maîtrise 
- [x] Criticité 2 Aspect Niveau d'influence Pourquoi et comment ?

Actions en cours comme pour la gestion des risques =

- [x] Mesures de prévention
- [x] Description de la mesure
- [x] Responsable Délais
