### ISSUE TITLE
9.3.3 Affichage Listing des Risques et Arborescence

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#1974]
Bonjour à tous,

J'ai déployé la 9.3.3 (merci pour les améliorations).

J'ai l'impression que l'on a un bug lié [https://github.com/Evarisk/Digirisk/commit/3c36f0811339e0a2bba886832f922701b89c53f2](https://github.com/Evarisk/Digirisk/commit/3c36f0811339e0a2bba886832f922701b89c53f2)

Fichier : digiriskdolibarr\class\digiriskelement.class.php

A priori, si on laisse le mot clé ranks, cela n'affiche pas les risques dans listing de risque chez moi, en modifiant en rank, cela fonctionne, je n'explique pas la raison.

`	/**
	 *  Return list of deleted elements
	 *
	 * 	@return    array  Array with ids
	 * 	@throws Exception
	 */
	public function getTrashList()
	{
		$objects = $this->fetchAll('',  '**rank**');
		if (is_array($objects)) {
			$recurse_tree = recurse_tree($this->id, 0, $objects);
			$ids          = [];

			array_walk_recursive($recurse_tree, function ($item) use (&$ids) {
				if (is_object($item)) {
					$ids[ $item->id] = $item->id;
				}
			}, $ids);

			return $ids;
		} else {
			return array();
		}
	}`

**Comment by evarisk-theo** [comment]
Bonjour,

Merci pour votre retour! Pouvez-vous vérifier qu'en base de données dans la table llx_digiriskdolibarr_digiriskelement votre colonne se nomme bien `ranks` et non `rank`?

**Comment by FredBl79** [comment]
> Bonjour,
> 
> Merci pour votre retour! Pouvez-vous vérifier qu'en base de données dans la table llx_digiriskdolibarr_digiriskelement votre colonne se nomme bien `ranks` et non `rank`?

Bonjour,

Oui j'ai vérifié avant, j'ai bien ranks dans la DB.

Cdlt
Fred

**Comment by evarisk-theo** [comment]
Nous allons voir de notre côté pour identifier d'où peut provenir le problème.

**Comment by evarisk-theo** [comment]
Rencontrez-vous encore ce problème depuis les mises à jour du module ?
