### ISSUE TITLE
Affichage en doublon des utilisateurs (affecté à 2 groupes)

### ISSUE THREAD

**Issue by aureliebourgeois** [Evarisk/Digirisk#2011]
b6770a6511225e1973253417ff3bec4069f08b52
**Vous avez trouvé un BUG ! Bravo !**
![image](https://user-images.githubusercontent.com/109142988/178461260-54030776-a544-4097-95ad-dbaa1ab0081a.png)

**Comment by JulienCregut** [comment]
La liste proposé par Dolibarr groupe par utilisateurs et non par les groupes, c'est plus cohérent.
![image](https://user-images.githubusercontent.com/109142969/178463347-941f2107-e7e7-4d7b-9cb1-56c808f0995a.png)
