### ISSUE TITLE
[Amélioration] Accident de travail, rajouter du JS sur la modifiation de la date debut d'accident de travail et la date de fin

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/Digirisk#2050]
Calculer en js, la nouvelle date de fin en fonction de la date de début et du nombre de jours
- [ ] en ajout
- [ ] en modification

**Comment by evarisk-micka** [comment]
- Créer trois champs libre remplissable par l'utilisateur #2184 
- Récupérer tous les champs remplissable d'un CERFA via API publique #2185
- Automatiser les données automatisable #2186
