### ISSUE TITLE
Impossible de créer un événement dans permis de feu

### ISSUE THREAD

**Issue by madizongo** [Evarisk/Digirisk#2140]
**Vous avez trouvé un BUG ! Bravo !**
Je n'arrive pas créer un événement sous l'onglet 'Evènements' de Permis de Feu.
Après avoir rempli le formulaire et cliqué sur le bouton "Ajouter...", on obtient une erreur 404. Mais je ne sais pas si c'est un bug ou c'est lié à ma configuration. 

**Vous pouvez décrire comment le reproduire ici**
Les étapes et le résultat attendu
1. Allez sur cette url idéalement 'https://votredomaine/comm/action/card.php?action=create&origin=firepermit@digiriskdolibarr&originid=1&backtopage=1&percentage=-1'
2. Click sur  'Ajouter'
3. Erreur 404'

**Copie d'écran**
On adore les copies d'écran afin de mieux comprendre
https://www.screenpresso.com/=9eWHe
https://www.screenpresso.com/=7dhAb

**Votre configuration sauf si vous êtes chez evarisk.com**
 - OS: Windows
 - Navigateur Edge
 - Version ?

**Smartphone **
 - Device: Android
 - Browser 
 - Version 

**Remarques**
Tous ce qui pourrait nous permettre de mieux comprendre ! Comme votre numéro de carte bancaire, le code :)

**Comment by lmag** [comment]
Pouvez vous préciser la version de Dolibarr et de DigiRisk
Arrivez vous à reproduire le bug sur la demo de DigiRisk ?

**Comment by madizongo** [comment]
Version Dolibarr : 15.0.2 DigiRisk : 9.4.0
Même chose sur la demo : https://www.screenpresso.com/=YhwIe

**Comment by lmag** [comment]
Merci pour le test, la correction est planifié pour la prochaine version
