### ISSUE TITLE
BUG - Option "signalisations partagées" non dispo

### ISSUE THREAD

**Issue by btestaniere** [Evarisk/Digirisk#2144]
**Vous avez trouvé un BUG ! Bravo !**
L'option n'est pas disponible dans les DU autres que ceux de Juvignac et Celleneuve

![image](https://user-images.githubusercontent.com/49953190/183374965-f7c0002d-887f-4813-8ae0-e9a1896e4742.png)

**Comment by lmag** [comment]
Pour information le module sera maintenant grisé lorsqu'il sera désactivé
