### ISSUE TITLE
[Dashboard] - Indicateurs Multisites générique

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2158]
**La description de la fonction attendue.**

![image](https://user-images.githubusercontent.com/3288514/183605911-2bc8d64e-1e10-46f9-93bc-1e558ec7f818.png)
https://user-images.githubusercontent.com/3288514/182882546-7756af68-0cee-4897-908d-ada9a7adb2cd.png

8858e7dc3feeec76e56ced28bdca369fcccf05b0

fb10625b28cee4a2102cff65f292603760628252

66b5d03e67764be3a13a15b5200740860a970fa0

6a91747a776d54874ba711cbb8a632aeaaf31bb5

1a34071be7bfdd0d985dcd846b85313948bd5aaa

17de56b805a55ca1a3d66f9f3945cfe609790b12

**Comment by lmag** [comment]
Pouvoir filtrer par Risques, par dates etc...

**Comment by lmag** [comment]
**SITE**
- N° SIRET
- DATE DUER
- Nombre de jour de retard
- "Nombre de salariés impliqués" = Evaluateurs
- "Risque faible"
- "Risque à planifier"
- "Risque à traiter"
- "Risque inacceptable"
- Nombre de jour(s) d'arrêt :

**Projet DU**
- Taches à 0%
- Tache en cours
- Taches à 100%
**Accident**
- Nombre de presque accident(s) :
- Nombre d'accident(s) :
- Nombre d'accidents/salarié
- Nombre d'enquête(s) :
- Enquête accident manquante :


**A préciser**
- Nombre de salariés : permettre une saisie manuelle à confirmer ?
- Nombre de causerie : permettre une saisie manuelle à confirmer ?
- Indice de fréquence (IF) = (nb des accidents en premier règlement/effectif salarié) x 1 000
- Taux de fréquence (TF) = (nb des accidents en premier règlement/Heures travaillées) x 1 000 000
- Taux de gravité (TG) = (nb des journées perdues par incapacité temporaire/heures travaillées) x 1 000
- Indice de gravité (IG) = (somme des taux d’incapacité permanente/heures travaillées) x 1 000 000

**Comment by evarisk-theo** [comment]
+ nombre de jours sans accident

**Comment by lmag** [comment]
à décaler et a baser sur les enquêtes accidents réalisées
 Nombre d'enquête(s) :
 Enquête accident manquante : #2497

**Comment by lmag** [comment]
Prévoir la connection sur les sites à piloter
