### ISSUE TITLE
Édition d'un risque avec cotation avancée - pas de surbrillance de la sélection précédente si le risque a été importé

### ISSUE THREAD

**Issue by btestaniere** [Evarisk/Digirisk#2159]
a0d7b910358f8546614d1e01282631eb75186b80

**Vous avez trouvé un BUG ! Bravo !**

**Copie d'écran**
![image](https://user-images.githubusercontent.com/49953190/183669368-98ef4e2f-c471-403d-ae40-328e655e45eb.png)

**Comment by lmag** [comment]
Import d'une nouvelle ancienne cotation ?

**Comment by btestaniere** [comment]
Avoir les cases de l'ancienne évaluation en surbrillance
