### ISSUE TITLE
Affichage photo d'un risque en plein écran

### ISSUE THREAD

**Issue by btestaniere** [Evarisk/Digirisk#2166]
**Vous avez trouvé un BUG ! Bravo !**

Lors du clic sur la photo d'un risque l’agrandissement marche temporairement ( 2x) que ce soit sur Firefox ou Chrome.
Après ce lien en bas de page apparait mais rien ne se passe.

![image](https://user-images.githubusercontent.com/49953190/184088495-e5b2c3c9-41cc-4c93-816b-0399388f7498.png)

**Comment by lmag** [comment]
Arrives tu a reproduire sur la démo ?
![image](https://user-images.githubusercontent.com/3288514/184148864-09e9c91a-140b-49c0-af6a-bd664a7482bd.png)
Ctrl+F5 sur le navigateur ?

**Comment by btestaniere** [comment]
Fonctionne temporairement (5min) mais sans scale après effacement des cookies sur Firefox
