### ISSUE TITLE
[Amélioration] Plusieurs médias sur un risque - impossible de faire défiler les photos

### ISSUE THREAD

**Issue by btestaniere** [Evarisk/Digirisk#2177]
**La description de la fonction attendue.**
![image](https://user-images.githubusercontent.com/49953190/185101341-e7fa30d3-a9db-4a10-852b-3f24cfcf4903.png)

![image](https://user-images.githubusercontent.com/49953190/185101445-09e7dd59-dd17-4002-98b7-ab6ab13b0d82.png)

**Comment by lmag** [comment]
Voir les améliorations avec l'intégration de Saturne DigiRisk 9.13
