### ISSUE TITLE
Risques partagés ne fonctionnent plus

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2228]
**Vous avez trouvé un BUG ! Bravo !**
![image](https://user-images.githubusercontent.com/3288514/187617269-6c9304b4-5112-488a-8e6f-ff72a210de20.png)

**Comment by evarisk-theo** [comment]
Fixé : 
2 raisons : 
- Vérifier que le partage est bien activé entre les entités 
- Si sur une des entités, Digirisk est désactivé, il faut désactiver/réactiver le module sur n'importe quelle entité
