### ISSUE TITLE
[Amélioration] - Conf par unité : Afficher l'unité de travail ou le GP dans la demande de ticket

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2238]
**La description de la fonction attendue.**
![image](https://user-images.githubusercontent.com/3288514/187892102-09a519b4-c9af-49c6-98f1-939c533644c9.png)

6ace94ffe6bca10be38fa44a99e1c3e89ec1884a

c324f039ecfadd64a34d9526881449fad00c187e

**Comment by evarisk-theo** [comment]
ajouter configuration par UT/GP "doit apparaitre dans la liste des elements de l'interface publique des tickets"
