### ISSUE TITLE
[Amélioration] - Unicité de l'adresse Email afin de limiter les doublons

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2290]
**La description de la fonction attendue.**
![image](https://user-images.githubusercontent.com/3288514/189119808-72792eea-d438-4712-a691-286d2f617005.png)

**Comment by nicolas-eoxia** [comment]
C'est déjà le cas 
![image](https://user-images.githubusercontent.com/52404047/190444933-5986101f-3dcc-495a-bf41-0f71e5caac07.png)
