### ISSUE TITLE
Champs personnalisés des tickets supprimés après mise à jours

### ISSUE THREAD

**Issue by madizongo** [Evarisk/Digirisk#2301]
0f005f4453a95efa42ca57250165729f4e8bb0a3

91ff27bfc315a2e8b88db91c010e687492993c31

Après mise à jours vers la version 9.5 toutes les données des champs personnalisées des anciens tickets créés via l'interface publique ont été supprimées. C'est pareil pour les nouveaux tickets. J'ai besoin de votre aide pour comprendre et résoudre le problème. Merci. 

Dolibarr : 15.02
Module Multicompany installé
Digirisk : 9.5
![2022-09-11_02h00_19](https://user-images.githubusercontent.com/104900838/189509259-8d87001b-902a-4e7a-8f70-c6f600a11cf5.png)
![2022-09-11_01h59_33](https://user-images.githubusercontent.com/104900838/189509261-00e31f16-9b5e-4f41-b407-5446b04b19ca.png)

**Comment by madizongo** [comment]
Pour ajouter, la table : [digiriskdolibarr_risk_extrafields] est vide. 

![2022-09-11_02h36_06](https://user-images.githubusercontent.com/104900838/189509824-6898bed1-94f9-49dc-9853-6a880a4aa05e.png)

**Comment by madizongo** [comment]
La Table: "llxml_ticket_extrafields" est complètement vide. 

![image](https://user-images.githubusercontent.com/104900838/189510610-0b30167b-705f-49b0-b579-327023b76776.png)

**Comment by evarisk-theo** [comment]
Bonjour,

Malheureusement, c'est un problème que nous n'avions pas identifié. Nous le corrigeons au plus vite dans la version 9.5.1 qui devrait sortir dans la semaine.

Si vous en avez la possibilité, nous vous invitons à remettre votre site en 9.4.0 ainsi qu'à restaurer les données telles qu'elles étaient à ce moment là.

Nous reviendrons vers vous lorsque ce problème sera corrigé.

**Comment by evarisk-theo** [comment]
Ce bug sera corrigé dans la 9.5.1 avec le commit 0f005f4453a95efa42ca57250165729f4e8bb0a3

**Comment by madizongo** [comment]
Ok. J'ai déjà rétrogradé et restauré la base de données. Merci.Le 12 sept. 2022 08:44, evarisk-theo ***@***.***> a écrit :

Bonjour,

Malheureusement, c'est un problème que nous n'avions pas identifié. Nous le corrigeons au plus vite dans la version 9.5.1 qui devrait sortir dans la semaine.

Si vous en avez la possibilité, nous vous invitons à remettre votre site en 9.4.0 ainsi qu'à restaurer les données telles qu'elles étaient à ce moment là.

Nous reviendrons vers vous lorsque ce problème sera corrigé.
