### ISSUE TITLE
Wysiwig

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2379]
Question florian

**Vous avez trouvé un BUG ! Bravo !**
![image](https://user-images.githubusercontent.com/3288514/191523727-ce6ec8a4-9b08-414c-8373-6f87e84b35e1.png)

**Comment by nicolas-eoxia** [comment]
Ce bug est fix dans la prochaine version 691977d1ed0afab411570258f6bb91c32b6b4f33
