### ISSUE TITLE
Erreur de date sur la génération il prends l'ancienne date

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2432]
**Vous avez trouvé un BUG ! Bravo !**
![image](https://user-images.githubusercontent.com/3288514/192617481-fbbb2fcb-f38b-462c-b102-d6aca3f0f899.png)

**Comment by evarisk-theo** [comment]
le nom dans la référence du document correspond à la date de génération du Document Unique
dans le document, la date d'audit affichée est la date d'audit enregistrée au moment de la génération, il est donc normal que le DU généré le 23/02 affiche une date d'audit du 23/02
