### ISSUE TITLE
[DataModel] - Enquêtes accidents

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2497]
**La description de la fonction attendue.**
Création des enquetes accidents (Nouvelle version de DigiRisk)
V0.0.1 : https://github.com/Evarisk/Digirisk/commit/39c95208b84df57491c1f0e4c51696a45c8a8e1a

**Comment by evarisk-micka** [comment]
- Ajouter une page enquête accident dans les accidents
- Ajouter dans les accidents / page enquête les champs requis par le ODT
- Faire attention à ne pas dupliquer les informations déjà présentes

- Demander à Laurent à quoi il veut que sa page ressemble

Actions correctives et préventives => Faire un tableau pour créer des tâches

**Comment by evarisk-micka** [comment]
Ancienneté dans l'entreprise (fetch user)
Ancienneté au poste de travail (new field)
Date et heure de l’accident (good)
Jour de la semaine (good)
Date de début de l’enquête accident (good)
Témoin(s) (good)
Travail posté (good)
Tâche habituelle (new field)
Il y a t'il déjà eu des accidents de travail sur le même poste (bool + check other accidents)
Il y a t'il déjà eu des presque-accidents sur le même poste (bool + check other accidents)


Tableau comportant les Nom Prénom Fonctions Société des

Personnes impliquées (good)
Personnes ayant participé à l’enquête (good)
Témoins (new field)


Tableau de Diplômes, formations, compétences: (DoliMeet ?):

Nom
Prénom
Diplomes/Formations/Compétences
Organisme certificateur
Date fin validité


Circonstances (new field)
Conséquences (new field) (ou celui des metadata)
Remarques (new field)

Secours appelé ? (new field)
Type de secours ? (new field : pompier/gendarme/police)
Qui a appelé les secours ? (new field)
Quand ont ils été appelé / (quand sont-ils arrivé ?) (new field)
Réalisée par la société employeur (good)
Le rapport d’accident a été envoyé le (good)


Tableau matériel impliqué (new object ?)
Tableau ITAMAMI (?)
Arbre des causes (?)


Action corrective / préventive (new task)

**Comment by lmag** [comment]
Données : 

- [x] Ancienneté dans l'entreprise (fetch user)
- [x] Date et heure de l’accident (fetch accident)
- [x] Jour de la semaine de l'accident (fetch accident)
- [x] Date de début de l’enquête accident (New)
- [x] Relié à une UT/GP (fetch accident)
- [x] Personnes ayant participé à l’enquête (New) (saturne_attendants)
- [x] Champs libre Compétences (New)
- [x] Circonstance accident (New) (possibilité de Fichier joint "Image")
- [x] Note publique (Remarque)
- [x] Note privée
- [x] Liaison au projet ACC
- [x] Liaison à la tache=enquete
- [x] Création tache corrective (Taches parentes)
- [x] Création tache curative -(Taches parentes)
- [x] Exemple de structures de taches
![image](https://github.com/Evarisk/Digirisk/assets/3288514/ac0b0a5b-6d8b-4757-bc01-4748e4d60f87)

Workflow agenda automatique

- [ ] Création de l'enquete
- [ ] Réalisée par la société employeur (good)
- [ ] Le rapport d’accident a été envoyé le (good)

--------------Vx -----------------
Données @vX
- [ ] Ancienneté au poste de travail (new field)
- [ ] Témoin(s)
- [ ] Travail posté
- [ ] Tâche habituelle
- [ ] Il y a t'il déjà eu des accidents de travail sur le même poste (bool + check other accidents)
- [ ] Il y a t'il déjà eu des presque accidents sur le même poste (bool + check other accidents)
- [ ] Si dolimeet : Id,Nom, Prénom, Diplomes/Formations/Compétences, Organisme certificateur, Date fin validité @vX
- [ ] Secours appelé ? (new field)
- [ ] Type de secours ? (new field : pompier/gendarme/police)
- [ ] Qui a appelé les secours ? (new field)
- [ ] Quand ont ils été appelé / (quand sont-ils arrivé ?) (new field)
- [ ] Tableau ITAMAMI vX
- [ ] Tableau matériel impliqué (new object ?)
