### ISSUE TITLE
autre proposition pour ajout utilisateur dans le cas de partage multi entité : créer l'utilisateur sur l'entité 1, l'affilier à un groupe et lui mettre les droits sur cette entité

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#2501]

**Comment by lmag** [comment]
Actuellement

![image](https://user-images.githubusercontent.com/3288514/193772213-8b817ae0-634a-4100-9960-ef411934df3a.png)

**Comment by lmag** [comment]
1 choix possible
2 choix non modifiable

**Comment by lmag** [comment]
Actuellement

![image](https://user-images.githubusercontent.com/3288514/193772213-8b817ae0-634a-4100-9960-ef411934df3a.png)

Sur le site qui a les contacts partagés

- [ ] Groupe "lecture" par défaut
- [ ] Le site utilisé (site connecté)

Si l'on souhaite ajouter en masse sur l'interface de DigiRisk sur le site maitre
On aura même comportement que sur un site classique
- [ ] Groupe "lecture" par défaut
- [ ] Le site utilisé (maitre)


![image](https://user-images.githubusercontent.com/3288514/193772723-1e1f30e4-2675-42c6-b904-6d9558b01269.png)
Zoom
![image](https://user-images.githubusercontent.com/3288514/193775678-a13a4814-516f-421b-9326-d410cb0f8f2c.png)
