### ISSUE TITLE
Contrôle sur les résultats des statistiques des tickets

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2572]
**Vous avez trouvé un BUG ! Bravo !**
![image](https://user-images.githubusercontent.com/3288514/194937264-20eb4eda-e055-46b5-b3b6-4701174140c6.png)

**Comment by nicolas-eoxia** [comment]
stats ok mais pas ergonomique
Renommer l'onglet fichiers -> export CSV 
Ficher csv -> Export des registres au format CSV associé à des GP/UT.
Fichiers joints le mettre dans par mois/années

par mois/années
quand gp/ut champs vide = tout 
quand les champs sont vides mettre tout 
mais faire aussi une requete champs vide pour les ticket sans gp/ut

 Remplacer année par la plage de date
