### ISSUE TITLE
[Amélioration] Fiche d'audit terrain

### ISSUE THREAD

**Issue by 0000N** [Evarisk/Digirisk#2631]
**La description de la fonction attendue.**
Réaliser des audits QSE et alimenter Digirisk : 
=> La donnée peut être traitée dans le plan d'action ; une ligne par écart.
=> Générer un projet "audits" ?
=> Générer un ticket par écart

Une autre solution (mieux) peut être envisagée.

**La description des données dont vous avez besoin**
Auditeur
Audités
Date
Unité de travail
Description de l'écart
Risque identifié
Évaluation de la criticité 
Proposition corrective (facultative)

**Les références légales ou normatives**
MASE / ISO 45001

**Les autres informations utiles**

**Comment by lmag** [comment]
Bonjour,

Super remarques nous avons un autre module pour faire cela : DoliSMQ ! l'avez vous testé
On pourrait y intégrer MASE, ISO45001, Marque NF etc...
Il faudrait adapter la notation des réponses

**Comment by 0000N** [comment]
Bonjour, 
j'ai essayé, mais "Modèle de contrôle" est grisé, donc je peux aller au bout. 

Mais si ce module peut être utilisé en complément, c'est super ! A creuser.

**Comment by lmag** [comment]
On va faire un tuto bientôt pour DoliSMQ
Etape 1 : Création des questions et verrouillage
![image](https://user-images.githubusercontent.com/3288514/196725820-b35798a2-f63f-4f0e-802a-0e7f22bb4bb1.png)
Etape 2 : Ajout des questions dans un formulaire de contrôle et surtout affectation a l'objet que l'on souhaite contrôler
![image](https://user-images.githubusercontent.com/3288514/196725981-44d3d086-cadb-4701-94cd-614e8a6bdcbd.png)
Etape 3 : Lance le contrôle sur l'objet
![image](https://user-images.githubusercontent.com/3288514/196726282-20c4e2ea-729d-4ec9-ac50-726404e70e12.png)
Etape 4 : Worklow avec les étapes de validation jusqu'a l'impression du rapport d'audit et la validation

**Comment by lmag** [comment]
Tout est disponible avec https://digiquali.com/
