### ISSUE TITLE
Création tickets depuis le module tickets

### ISSUE THREAD

**Issue by 0000N** [Evarisk/Digirisk#2635]
Bonjour, 
Je ne sais pas si c'est vraiment un bug ou c'est paramétré ainsi :
**En passant par le module ticket, le menu déroulant "Catégorie" est vide, j'ai essayé de créer les catégorie dans le dictionnaire mais sans succès.** 

______________________________________

**Copie d'écran**
![image](https://user-images.githubusercontent.com/115844632/197046432-4adc1b89-e106-481b-b191-4566f51061dd.png)

**Comment by lmag** [comment]
A voir plutôt dans les paramètres ;)
