### ISSUE TITLE
Erreur de token

### ISSUE THREAD

**Issue by 0000N** [Evarisk/Digirisk#2653]
5a15c5b68a8935fcdd54a6beb3cfb9b1ce6e044c
custom/digiriskdolibarr/admin/config/digiriskelement.php?action=setmod&value=mod_groupment_sirius&type=groupment&scan_dir=&label=Sirius

Access to this page this way (POST method or GET with a sensible value for 'action' parameter) is refused by CSRF protection in main.inc.php. Token not provided. If you access your server behind a proxy using url rewriting and the parameter is provided by caller, you might check that all HTTP header are propagated (or add the line $dolibarr_nocsrfcheck=1 into your conf.php file or MAIN_SECURITY_CSRF_WITH_TOKEN to 0 instead of 2 into setup).

**Comment by 0000N** [comment]
Manque token "MAIN_SECURITY_CSRF_WITH_TOKEN"

**Comment by lmag** [comment]
ok en cours
