### ISSUE TITLE
bug document unique

### ISSUE THREAD

**Issue by 3safe** [Evarisk/Digirisk#2682]
**Vous avez trouvé un BUG ! Bravo !**
Vous pouvez décrire votre bug ici
![Capture d’écran 2022-11-04 212227](https://user-images.githubusercontent.com/117483749/200067990-026494e4-dcca-4815-a5c8-3d44481d657c.png)
<html>
<body>
<div id="id-container" class="id-container" style="display: table; table-layout: fixed; color: rgb(0, 0, 0); font-family: arial, tahoma, verdana, helvetica; font-size: 14.72px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="id-right" style="display: table-cell; float: none; vertical-align: top; padding-top: 14px; width: 1671px; background: var(--colorbackbody); padding-bottom: 20px;"><div class="fiche" style="margin-left: 40px; margin-right: 36px;"><div id="id-container" class="id-container page-ut-gp-list" style="margin-left: -30px; box-sizing: border-box; width: 1595px; display: table; table-layout: fixed;"><div id="id-right" style="box-sizing: border-box; display: block; float: none; vertical-align: top; padding-top: 14px; width: calc(100% + 30px); background: var(--colorbackbody); padding-bottom: 20px; padding-left: 300px;"><div class="fiche" style="box-sizing: border-box; margin-left: 40px; margin-right: 0px !important;"><div id="cardContent" value="" style="box-sizing: border-box;"><div class="tabBar" style="box-sizing: border-box; color: var(--colortextbacktab); padding: 16px 0px 2px; margin: 0px 0px 16px; border-top: 1px solid rgb(187, 187, 187); width: auto; background: var(--colorbacktabcard1);"><div class="fichecenter risklist wpeo-wrap" style="box-sizing: border-box; width: 1285px; clear: both;"><form method="POST" id="searchFormListRisks" enctype="multipart/form-data" action="http://127.0.0.1/dolibarr/custom/digiriskdolibarr/view/digiriskelement/digiriskelement_risk.php?id=4" style="padding: 0px; margin: 0px; box-sizing: border-box;"><div class="div-title-and-table-responsive" style="box-sizing: border-box;"><div class="div-table-responsive" style="overflow-x: auto; min-height: 0.01%; line-height: 17.664px; box-sizing: border-box;">

Warning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103RA5 04/11/2022SRISKASSESSMENTMEDIAS RA5 Ajouter un médiaPhotoWarning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103MediasPas de média lié FermerÉDITION DE L'ÉVALUATION RA5Cotation simple Cotation avancée   Ajouter un média Sélectionnez les cases pour calculer votre cotation01234GravitePas de blessure possibleBlessure légèreITT<5 jours ou effet réversibleITT>5jours ou effet irréversibleMenace sur la vieExpositionJamais en contactRare, 1 fois par anInhabituelle, 1 fois par moisOccasionnelle, 1 fois par semaineFréquente, 1 fois par jourOccurrenceJamais arrivéEst déjà arrivé dans des circonstances exceptionnellesS'est produit 2 foisSe produit tous les moisFormationPrévention régulièreFormation individuelle obligatoireFormation obligatoire non réaliséePas de formation ni de préventionProtectionIntrinsèqueCollectiveIndividuelleRienPhotoWarning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103 Cotation calculée35 CommentaireDate MaintenantMediasPas de média lié Mettre à jourLISTE DES ÉVALUATIONS DU RISQUE RK635Warning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103RA5 04/11/2022SFermerAJOUT DE L'ÉVALUATION RA6Cotation simple Cotation avancée   Ajouter un média Sélectionnez les cases pour calculer votre cotation01234GravitePas de blessure possibleBlessure légèreITT<5 jours ou effet réversibleITT>5jours ou effet irréversibleMenace sur la vieExpositionJamais en contactRare, 1 fois par anInhabituelle, 1 fois par moisOccasionnelle, 1 fois par semaineFréquente, 1 fois par jourOccurrenceJamais arrivéEst déjà arrivé dans des circonstances exceptionnellesS'est produit 2 foisSe produit tous les moisFormationPrévention régulièreFormation individuelle obligatoireFormation obligatoire non réaliséePas de formation ni de préventionProtectionIntrinsèqueCollectiveIndividuelleRienPhotoWarning: is_dir(): open_basedir restriction in effect. File(/riskassessment/(PROV6)) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103 Cotation calculée*0 CommentaireDate MaintenantMediasPas de média liéDernière évaluation du risque RK635Warning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103RA5 04/11/2022S Ajouter | Liste des tâches (0) Pas de tâche en coursAJOUT DE LA TÂCHE TK2211-0003 AU PROJET PJ2208-0001Libellé  AjouterLISTE DES TÂCHES DU RISQUE RK6 AU PROJET PJ2208-0001Fermer |  
-- | -- | --

</div></div></form></div></div></div></div></div></div></div></div></div><br class="Apple-interchange-newline">
</body>
</html>
**Vous pouvez décrire comment le reproduire ici**
Les étapes et le résultat attendu
1. Allez sur cette url idéalement 'https://votredomaine/custom/digiriskdolibarr/view/digiriskstandard/digiriskstandard_card.php...'
2. Click sur  '....'
3. Etc '....'

**Copie d'écran**
On adore les copies d'écran afin de mieux comprendre

**Votre configuration sauf si vous êtes chez evarisk.com**
 - OS: [e.g. iOS] w10 et w11
 - Navigateur [e.g. chrome, safari] chrome et opera

**Smartphone **

**Remarques**
Tous ce qui pourrait nous permettre de mieux comprendre ! Comme votre numéro de carte bancaire, le code :)
Warning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103
No photo
RA5
 04/11/2022
[S](http://127.0.0.1/dolibarr/user/card.php?id=1)
RISKASSESSMENTMEDIAS RA5
 Ajouter un média
Photo

Warning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103
No photo
Medias
Pas de média lié
 Fermer
ÉDITION DE L'ÉVALUATION RA5
Cotation simple Cotation avancée   Ajouter un média
 Sélectionnez les cases pour calculer votre cotation
0
1
2
3
4
Gravite
Pas de blessure possible
Blessure légère
ITT<5 jours ou effet réversible
ITT>5jours ou effet irréversible
Menace sur la vie
Exposition
Jamais en contact
Rare, 1 fois par an
Inhabituelle, 1 fois par mois
Occasionnelle, 1 fois par semaine
Fréquente, 1 fois par jour
Occurrence
Jamais arrivé
Est déjà arrivé dans des circonstances exceptionnelles
S'est produit 2 fois
Se produit tous les mois
Formation
Prévention régulière
Formation individuelle obligatoire
Formation obligatoire non réalisée
Pas de formation ni de prévention
Protection
Intrinsèque
Collective
Individuelle
Rien
Photo

Warning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103
No photo
 Cotation calculée
35
 Commentaire
Date
04/11/2022
... Maintenant
Medias
Pas de média lié
 Mettre à jour
LISTE DES ÉVALUATIONS DU RISQUE RK6
35

Warning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103
No photo
RA5
 04/11/2022
[S](http://127.0.0.1/dolibarr/user/card.php?id=1)
Fermer
AJOUT DE L'ÉVALUATION RA6
Cotation simple Cotation avancée   Ajouter un média
 Sélectionnez les cases pour calculer votre cotation

0
1
2
3
4
Gravite
Pas de blessure possible
Blessure légère
ITT<5 jours ou effet réversible
ITT>5jours ou effet irréversible
Menace sur la vie
Exposition
Jamais en contact
Rare, 1 fois par an
Inhabituelle, 1 fois par mois
Occasionnelle, 1 fois par semaine
Fréquente, 1 fois par jour
Occurrence
Jamais arrivé
Est déjà arrivé dans des circonstances exceptionnelles
S'est produit 2 fois
Se produit tous les mois
Formation
Prévention régulière
Formation individuelle obligatoire
Formation obligatoire non réalisée
Pas de formation ni de prévention
Protection
Intrinsèque
Collective
Individuelle
Rien
Photo

Warning: is_dir(): open_basedir restriction in effect. File(/riskassessment/(PROV6)) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103
No photo
 Cotation calculée*
0
 Commentaire
Date
04/11/2022
 Maintenant
Medias
Pas de média lié
Dernière évaluation du risque RK6
35

Warning: is_dir(): open_basedir restriction in effect. File(/riskassessment/RA5) is not within the allowed path(s): (c:/dolibarr) in C:\dolibarr\www\dolibarr\htdocs\core\lib\files.lib.php on line 103
No photo
RA5
 04/11/2022
[S](http://127.0.0.1/dolibarr/user/card.php?id=1)
 Ajouter
Liste des tâches (0)
 
Pas de tâche en cours
AJOUT DE LA TÂCHE TK2211-0003 AU PROJET [PJ2208-0001](http://127.0.0.1/dolibarr/projet/card.php?id=1)
Libellé 
 Ajouter
LISTE DES TÂCHES DU RISQUE RK6 AU PROJET [PJ2208-0001](http://127.0.0.1/dolibarr/projet/card.php?id=1)
Fermer

**Comment by 3safe** [comment]
Bonsoir Théo, je suis la personne qui vous avait téléphoné cette apres-midi. Cordialement. c'est la même erreur que nous avons chez un client cette après-midi, je viens de tester la version en local chez moi et l'erreur se reproduit aussi

**Comment by evarisk-theo** [comment]
Bonjour,

Merci d'avoir remonté ce bug.
Sur votre serveur local, dans le php.ini (c:dolibarr/bin/php/your-php-version/php.ini) commentez la ligne "open_basedir" en ajoutant un ; devant comme sur l'image ci-après: 
![image](https://user-images.githubusercontent.com/68421590/200535067-c61bfe60-20d2-4d56-997d-22354842fd02.png)

Dans le cas d'un serveur hébergé en ligne, vérifiez la valeur de la variable open_basedir dans le fichier php.ini afin de l'adapter pour qu'elle autorise l'accès aux fichiers stockés dans le dossier "documents" de Dolibarr

**Comment by 3safe** [comment]
Bonsoir Théo,

J'ai essayé ce que tu m'as mis (cf screenshot) cependant cela ne change pas
le bug.

Cordialement.

Morgan

Le mar. 8 nov. 2022 à 11:02, evarisk-theo ***@***.***> a
écrit :

**Comment by evarisk-theo** [comment]
Bonjour,

Malheureusement, il est difficile de corriger ce problème.
Je peux vous conseiller de passer la valeur de "display_errors" dans votre fichier php.ini à "Off", cela masquera les erreurs que vous voyez.

Autrement, nous proposons des solutions d'hébergement pour lesquelles vous pouvez retrouver les tarifs ici : https://www.digirisk.com/tarifs/digirisk-en-mode-saas

Avec ces offres, vous aurez la possibilité d'accéder à votre Digirisk depuis n'importe où et vous ne rencontrerez pas d'erreurs de ce type.
