### ISSUE TITLE
[TXT] - Faute traduction

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2683]
** Remarques questions tous sauf BUG et Améliorations **
![image](https://user-images.githubusercontent.com/3288514/200498450-cb9836ed-e252-4fd5-bdfa-eea8392c4c0a.png)

**Comment by lmag** [comment]
@evarisk-micka invalid ??

**Comment by evarisk-micka** [comment]
@lmag erreur de traduction dans la description du risque (la description est remplie à la main par l'utilisateur)
La faute ne vient pas de nous mais du remplissage de la description (faute de frappe dû à l'utilisateur)
