### ISSUE TITLE
Logo société sur interface publique

### ISSUE THREAD

**Issue by 0000N** [Evarisk/Digirisk#2713]
3c0977e21891bd253e4b1fa03ba5003b531d43f7
aab55824a643aa52d2df320c9c73732576736368

Bonjour, 

J'ai activé l'option pour afficher les logos des sociétés, mais cette option fonctionne uniquement sur l'environnement n°1 du multisociété.

![image](https://user-images.githubusercontent.com/115844632/202123497-ccb1468e-e617-45fb-9f33-dcc370ab53e9.png)

**J'ai essayé sur plusieurs instances et sur "mondoli" et le logo de la société ne s'affiche pas.**

**Comment by nicolas-eoxia** [comment]
J'ai effectué le test sur 2 entités les logos de la société, pour le moment on récupère ce type de logo : 
![image](https://user-images.githubusercontent.com/52404047/203667833-ec6283a2-02cd-4514-a5c6-8d1ee5a0d4f3.png)

**Comment by 0000N** [comment]
Bonjour, 

Pour reproduire l'erreur, il faut vous mettre en navigation privée.
Je viens de le refaire, le logo de l'environnement principal apparait bien mais pas celui du 2e environnement.

Cordialement,
