### ISSUE TITLE
Suppression GP

### ISSUE THREAD

**Issue by 0000N** [Evarisk/Digirisk#2735]
Bonjour, 

Quand j'essaie de supprimer un GP dans le document unique j'ai le message suivant : 

`Access to this page this way (POST method or GET with a sensible value for 'action' parameter) is refused by CSRF protection in main.inc.php. Token not provided. If you access your server behind a proxy using url rewriting and the parameter is provided by caller, you might check that all HTTP header are propagated (or add the line $dolibarr_nocsrfcheck=1 into your conf.php file or MAIN_SECURITY_CSRF_WITH_TOKEN to 0 instead of 2 into setup). `

**Comment by 0000N** [comment]
J'ai ajouté cette variable en valeur "0" : 

MAIN_SECURITY_CSRF_WITH_TOKEN

**Comment by evarisk-theo** [comment]
Bonjour,

Effectivement, le problème apparaît depuis la version 16.0.0 et se corrige de cette manière. Cette issue doit être corrigée dans la prochaine version à venir, vous pourrez voir son évolution ici : https://github.com/Evarisk/Digirisk/issues/2694
Merci à vous pour votre retour
