### ISSUE TITLE
[Amélioration] - Manque le Budget des actions dans le DU

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2754]
2e1ec0e131ad57e9fcf1d0d4514ad64d064959e3

**La description de la fonction attendue.**
![image](https://user-images.githubusercontent.com/3288514/203354965-9f824e49-7c45-43c5-8b6e-324af3a7bec9.png)

**Comment by evarisk-micka** [comment]
2e1ec0e131ad57e9fcf1d0d4514ad64d064959e3
