### ISSUE TITLE
Ajout des tags et catégorie sur les accidents

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2757]
Il serait possible de créer : 

- [ ] Catégorie métiers
- [ ] Catégorie Statistique Accident (a comparer avec les statistiques officiels)

review 23/11 :

**Comment by nicolas-eoxia** [comment]
il y a des petites imprécisions a fix

**Comment by evarisk-micka** [comment]
- [x] ne pas fetch l'object quand clone 
- [x] enquete accident enlever de accident dans leftmenu
- [x] 100+r (!= 1000+r)
- [x] maxwidth500 maxwidth80percent
