### ISSUE TITLE
Améliorer l'interface de public des tickets

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/Digirisk#2816]
a8e8a094499cecede6898eff82c930375431301c
dfa4ea0e0a36abb9d51c0401af1d168c3df3aa72
264d84c7354ef3d9c10f4f8a9bf8e0f198a58581
03adb9d5710646ce1e3b38f99e4439dd046698cf
c5338d647551c745c9bf48570b3f1d1df2330024
26a682987656d81c602b5a29d3371df1529a8c91

- [x] champs visibleS ticket.php
- [x]  new DigiriskElement en haut du fichier à l'endroit ou on initialise les objets
- [x] enlever le doublon de code dans actions_digiriskdolibarr sur le champ digiriskelement
- [x] pareil pour le champ email
- [x] dolibarr_get_const pour les conf extrafields entity 0 
- [x] ajouter un check sur la visibilité de digiriskelement
- [x] ajouter js sur la regex téléphone ou l'enlever du php 

Bonjour,
 
Pour faire suite à la présentation de l’outil de ticketing ([copac.fr/help](http://copac.fr/help)).
Je reviens vers vous afin de rendre plus accessible l’interface des tickets.
 
Supprimer le choix des sites (non pertinent) :

 
![image](https://user-images.githubusercontent.com/52404047/205381385-dd619586-b94a-4b9c-91fc-3d3a78f390bf.png)

Conserver uniquement les champs : Email, Téléphone, Registre et Message (Le message ne doit pas être obligatoire).
 
![image](https://user-images.githubusercontent.com/52404047/205381401-28ade648-8468-4b2e-bfcf-4c3ee7d81305.png)

 
Je précise que l’ensemble des vues ont été validées par Alexandre KAR.
En vous remerciant par avance,

**Comment by 0000N** [comment]
Bonjour, 

C'est possible de garder une option pour activer l'affichage des GP/UT ?
En effet, cette liste est utile quand on recense dans le document unique des machines qui représentent une unité de travail.

Cordialement,

**Comment by rkerviel** [comment]
Bonjour,

L'informatique n'a pas les mêmes besoins que la qualité pour le DUER.
S'il s'agit d'améliorations payantes, nous utiliserons un autre moyen de ticketing.
Si non, nous avons besoin d'une seule entrée et pas d'obligations sur les services, le nom/prénom mais uniquement une obligation sur l'adresse mail. A KAR qui utilise le compte de Roman. Merci.

**Comment by lmag** [comment]
Pas d'inquiétude @0000N ce ne sera pas cette option qui sera choisie :)
L'interface des Ticket peut aussi être traitée dans le natif de Dolibarr pour le traitement des tickets informatiques
