### ISSUE TITLE
Encodage des "é" n'est pas correcte sur les formats *.odt

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#2873]
cef16e728e3516cc0a3d2f9a1a6533e70afa9edb

### Bug

Il existe des différents accents aigus "é" n'est pas encodé correctement sur les modèles *.odt
Notamment l'accent de "éch"é"ance" dans les plans d'actions

### Environment Version

Tous

### Expected and actual behavior

Résolution réalisées : 
Ouvrir le fichier avec OpenOffice
Ctrl +F rechercher "é" remplacé par "é" tapé au clavier
CRTL + S

### Steps to reproduce the behavior

Bon courage ! :

**Comment by nicolas-eoxia** [comment]
finalement il faut transnoentities deadline
