### ISSUE TITLE
[Amélioration] Catégories/Tags non visible dans la liste des Tickets

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#2877]
Bonjour,

Actuellement quand vous ouvrez la liste des tickets, il n'y a aucun moyen d'avoir l'info du registre/enfant dans le menu 'liste ticket'
Dans le cadre de Digirisk, les tags sont utilisés pour classifier et donc type/catégorisation de Dolibarr sont à "autres".
Pourriez vous voir pour avoir une liste des tickets Digirisk avec leur catégories/tag pour avoir une vue complète des tickets

Merci
Fred

**Comment by nicolas-eoxia** [comment]
Bonjour, 

Dans la liste des tickets, si on choisi de voir tout les tickets qui ont pour catégorie Registre (catégorie crée par Digirisk).
On observe bien l'information souhaité
![image](https://user-images.githubusercontent.com/52404047/208934524-22da0e5f-43f6-4c84-89da-a561aa4ba1d4.png)

Si jamais on souhaite avoir l'informations par rapport a chaque GP/UT
![image](https://user-images.githubusercontent.com/52404047/208935316-e6f541fb-3ffe-46af-bdc3-d2bc454716e1.png)

De plus, si on veux des infos plus globales, il y a le tableau de bord des tickets
![image](https://user-images.githubusercontent.com/52404047/208935673-90e0cab3-5f2a-45ea-9599-ee512c75b66d.png)

Est-ce qu'au moins une de ces 3 vues répondent à la problématique ?

Nicolas

**Comment by FredBl79** [comment]
Bonjour @nicolas-eoxia 

Merci, oui on devrait s'en sortir avec la première vue et recherche par tag.

Je me demandais si la custo des tags (enfants de registre) est autorisée ou cela impactera le fonctionnement du module ?
Ajout de plusieurs enfants sous registre, modification des enfants d'accidents.

merci
Fred

**Comment by nicolas-eoxia** [comment]
Bonjour @FredBl79

Parfait, oui il est tout a fait possible de modifier les enfants, (en rajouter/modifier les données/en supprimer).
De plus, on peut aussi modifier la catégorie principale ciblée pour récupérer une autre liste d'enfants par exemple

![image](https://user-images.githubusercontent.com/52404047/209557030-852b4f7f-a0d1-42f8-959a-da1184f7a012.png)

Nicolas

**Comment by FredBl79** [comment]
> Bonjour @FredBl79
> 
> Parfait, oui il est tout a fait possible de modifier les enfants, (en rajouter/modifier les données/en supprimer). De plus, on peut aussi modifier la catégorie principale ciblée pour récupérer une autre liste d'enfants par exemple
> 
> ![image](https://user-images.githubusercontent.com/52404047/209557030-852b4f7f-a0d1-42f8-959a-da1184f7a012.png)
> 
> Nicolas

Merci beaucoup, j'ai généré une nouvelle liste en fonction de nos besoins pour MASE. Il me reste encore à créer la hiérarchie de répertoires IMG pour récupérer les icones des registres et des sous catégories.

Bonne journée
Fred
