### ISSUE TITLE
[Amélioration] Interface publique des tickets - On ne voit pas la ligne service.

### ISSUE THREAD

**Issue by ocemag** [Evarisk/Digirisk#2891]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/41377034/210246187-3e44c879-a45f-48ed-8d58-ddb087e7824d.png">

**Comment by ocemag** [comment]
Il faudrait la mettre plus gros ou l'espacer plus des blocs de couleur.

**Comment by evarisk-theo** [comment]
Bonjour @ocemag,

Merci pour votre retour! C'est corrigé dans la version 9.9.0
