### ISSUE TITLE
[Amélioration] Ticket/Interface publique : Envoi d'un email de confirmation avec détails du ticket au créateur si email rempli

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#2902]
Actuellement, le créateur d'un ticket n'est pas informé et n'a pas la possibilité de consulter ses tickets ouverts.
Serait il possible que lors de la création d'un ticket via interface publique, il soit en copie de l'email envoyé au responsable (configuré dans digirisk->ticket) si le créateur a rempli son email dans le ticket

**Comment by lmag** [comment]
Bonjour,
Ces fonctions sont des fonctions natives de Dolibarr il suffit de les configurer. Nous pouvons aussi mettre en place un acces spécifique pour le portail externe.
A votre disposition si vous avez besoin d'aide sur ce sujet
Laurent
