### ISSUE TITLE
rework css modal tâche

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#2927]
3c5c88d0b151881a77f88d5af6a3e73a87906004
e47a1fc7cf5175ab27600652a96e02b615b02641

**Comment by evarisk-micka** [comment]
Bon CSS à avoir
![image](https://user-images.githubusercontent.com/111346550/213455678-33c867f2-87c4-4ec5-86ea-312e12629cc5.png)
![image](https://user-images.githubusercontent.com/111346550/213455329-ca1c9119-191b-49e2-9e14-ac9edf8def6b.png)

Mauvais CSS actuel
![image](https://user-images.githubusercontent.com/111346550/213455610-73277114-29cf-465d-bc33-5ff8d85f470e.png)
![image](https://user-images.githubusercontent.com/111346550/213455435-34dd647f-5fd6-412d-8f47-a869ecbe0cfb.png)
