### ISSUE TITLE
Copier ensemble de risques vers autre unité de travail [Amélioration]

### ISSUE THREAD

**Issue by lvourey** [Evarisk/Digirisk#2944]
Il serait utile de pouvoir copier/déplacer des risques vers des Unités de travail ou des groupes sans avoir besoin de le recréer.
Je n'ai pas trouvé comment le faire.
Pouvoir sélectionner un risque déjà créé et évalué puis avoir l'option de le "dupliquer ou le déplacer vers" et avoir le choix dans l'arborescence de sa destination.
Ceci ferait gagner pas mal de temps.

**Comment by lvourey** [comment]
Pour le moment la seule action qui est proposée lorsque l'on sélectionne le risque (case de droite) c'est la suppression.
J'ai créé un certain nombre de risques dans une unité de travail et me rendant compte qu'ils sont commun à plusieurs unité de travail au sein d'un même groupe, je souhaiterais faire remonter (déplacer) ces risques vers le groupe parent.

**Comment by nicolas-eoxia** [comment]
Bonjour @lvourey,

L'option de déplacement d'un risque se trouve dans la configuration.
![image](https://user-images.githubusercontent.com/52404047/214537471-55a025e6-7a0f-4b95-8864-930baa1c5e20.png)
Une fois l'option activée rendez-vous dans votre GP/UT.
![image](https://user-images.githubusercontent.com/52404047/214537791-9018e515-4c76-4078-a71b-83175a855e88.png)
![image](https://user-images.githubusercontent.com/52404047/214537836-3dfda35f-b2a7-4234-af83-9f815beb3d06.png)

**Comment by lvourey** [comment]
Top!
Je n'avais pas vu que le menu configuration changeait en fonction de
l'onglet sur lequel on se trouvait!
Je trouvais effectivement étrange que ça ne soit pas possible.
Merci et bonne journée.
