### ISSUE TITLE
[Amélioration] Partage templates pour DUER

### ISSUE THREAD

**Issue by lvourey** [Evarisk/Digirisk#2956]
Bonjour.
Le template de DUER par défaut liste les risques (et action associées) par importance, en mélangeant les unités de travail et les groupes.

Je souhaiterais savoir s'il existe d'autres templates permettant de compiler le même DUER :
- en respectant l'arborescence puis au sein de chaque unité de travail par importance de risque => plus lisible pour l'inspection du travail) 
- en rassemblant tous les risques par typologie de risque (ex: tous les risques incendie, tous les risques de chute etc...) => simplifie le chiffrage des plans d'actions par thématique

Je ne me sens pas suffisamment compétent pour modifier un template existant pour créer mon propre template.

**Comment by evarisk-theo** [comment]
Bonjour @lvourey,

Merci pour votre retour.
Par défaut et selon la loi, le Document Unique doit afficher les risques triés par cotation décroissante, il n'est donc pas possible de modifier le Document Unique. 
Cependant, il est prévu dans les prochaines versions de Digirisk de créer un document qui sortira la liste de risques, cette fois triée par groupement et unité de travail donc bien en fonction de l'arborescence.
Concernant le document contenant les risques triés par typologie de risques, ce n'est pas prévu pour le moment.
