### ISSUE TITLE
Problème signature PDP

### ISSUE THREAD

**Issue by 0000N** [Evarisk/Digirisk#3016]
Bonjour, 

J'ai créé un PdP, signé informatiquement depuis l'interface mondoli, mais l'état reste en "Validé (en attente de signature"
![image](https://user-images.githubusercontent.com/115844632/219333267-4a8fff19-a657-432c-a6ab-eda1900796db.png)

**Comment by evarisk-theo** [comment]
Bonjour @0000N,

Merci pour votre retour.
Une fois que les participants ont signé, pour changer le statut du plan de prévention, il faut cliquer sur le bouton "Verrouiller" sur la fiche du plan de prévention
