### ISSUE TITLE
9.9.0 Bug generation des ODT en Dolibarr 16.0.4

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#3072]
### Bug

Bonjour,

La substitution ne fonctionne pas sous Dolibarr 16.0.4 dans la génération des ODT, cela est lié au fait que dans le code il y a un test en dur sur la version Dolibarr

/class/digiriskdocuments.class.php

if (version_compare(DOL_VERSION, '16.0.2', '<=')) {
			$this->element = $this->element . '@digiriskdolibarr';
		}

Je ne sais pas quel est l'impact de tester la version de Dolibarr ? 
j'ai corrigé chez moi et la génération des ODT refonctionne

Fred

### Environment Version

16.0.4

**Comment by nicolas-eoxia** [comment]
Bonjour, @FredBl79

Effectivement, on a rencontré un problème lié à ça, en voulant upgrade les version de Dolibarr, 
Le problème est corrigé dans la prochaine version.

Bonne journée,
Nicolas

**Comment by FredBl79** [comment]
merci pour le retour @nicolas-eoxia  !
