### ISSUE TITLE
Génération du document unique - Liste de tickets, {categories} n'est pas vidé à chaque ligne de ticket

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#3108]
### Bug

Bonjour,

En 9.9.0, la colonne categories des tickets dans l'ODT généré semble être incrémenté à chaque ligne de ticket. Nous nous retrouvons avec un fichier de 400 pages au final. 

j'ai l'impression que {categories} ne se vide pas à chaque ligne de tickets, il n'y que le 1er ticket qui est correct ensuite, il incrémente la chaine de caractère à chaque ligne.

### Environment Version

16.0.4

**Comment by lmag** [comment]
Avez-vous fait un test sur la dernière version ?

**Comment by FredBl79** [comment]
Bonjour,

Je suis en 9.9.0 oui

Fred

**Comment by nicolas-eoxia** [comment]
Bonjour, @FredBl79

Merci de votre participation

Cette issue sera corrigé dans la version 9.11
Voici le commit de correction : 2580153a74025bdd98c45070705df2cda8ee0f89

Bonne journée,

Nicolas
