### ISSUE TITLE
[Amélioration] - Valorisation d'un ticket

### ISSUE THREAD

**Issue by ludovic3859** [Evarisk/Digirisk#3118]
**La description de la fonction attendue.**
J'aimerais que lorsqu'un ticket est créer, on puisse y attribuer une estimation de coût. 
Objectif : Pouvoir quantifier le coût total recensé dans les registres

**Comment by lmag** [comment]
Voir la notion de la monnaie
![image](https://user-images.githubusercontent.com/3288514/231415469-00f6cc43-a5a6-46f9-a725-a10620a7e5a4.png)

**Comment by lmag** [comment]
Intégration dans les statistiques avec la vue mensuelle par coût
![image](https://user-images.githubusercontent.com/3288514/231416774-fab2372a-5502-4ac0-9ca5-62bba2af1977.png)
