### ISSUE TITLE
Problème génération des tickets dans le DU

### ISSUE THREAD

**Issue by 0000N** [Evarisk/Digirisk#3120]
37e3cbf3677a624fbd22940f3037d097184431c5

Bonjour, 

J'ai configuré des tags personnalisés dans l'environnement public pour les tickets, cependant lorsque je génère le document unique, il affiche tous les tags dans chaque ligne de ticket. 

![image](https://user-images.githubusercontent.com/115844632/232018721-c6d273cd-e6ab-46ac-b2c6-b23f11ebde35.png)

![image](https://user-images.githubusercontent.com/115844632/232017345-549a5767-d023-49f5-a0ed-7c375c1f2bbd.png)

**Comment by evarisk-theo** [comment]
Bonjour,

Nous avons bien pris en compte votre retour, ce bug sera corrigé dans la version 9.11.0 de Digirisk.

**Comment by nicolas-eoxia** [comment]
Bonjour, @0000N

Merci de votre participation

Cette issue sera corrigé dans la version 9.11
Voici le commit de correction : 37e3cbf3677a624fbd22940f3037d097184431c5

Bonne journée,

Nicolas
