### ISSUE TITLE
Tickets - Statistiques et tableau de bord 

### ISSUE THREAD

**Issue by 0000N** [Evarisk/Digirisk#3124]
2580153a74025bdd98c45070705df2cda8ee0f89

Bonjour, 

Lorsqu'on va sur le tableau de bord, les premiers indicateurs qu'il affiche sont erronés, il faut rafraichir la page pour retrouver les bonnes informations : 

### Avant de rafraichir : 
![image](https://user-images.githubusercontent.com/115844632/235612771-2d0e7f45-dd98-4930-ad49-6736c98742d6.png)

### Après avoir rafraichi : 
![image](https://user-images.githubusercontent.com/115844632/235612885-281ff2cd-202d-40fe-b8a2-7122d52c11e5.png)

**Comment by nicolas-eoxia** [comment]
Bonjour, @0000N

Merci de votre participation

Cette issue sera corrigé dans la version 9.11
Voici le commit de correction : https://github.com/Evarisk/Digirisk/commit/2580153a74025bdd98c45070705df2cda8ee0f89

Bonne journée,

Nicolas
