### ISSUE TITLE
9.10.0 : Problème de format de la fiche évaluation

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#3138]
### Bug

Bonjour,

Il semble que le format de la fiche évaluation ne soit pas correctement gérée : 

Couleur des textes sélectionnés en blanc sur blanc
Bouton mettre à jour se retrouve hors de la fenêtre (obligation de  dezoom)

![image](https://github.com/Evarisk/Digirisk/assets/100215218/10a08d3c-fd53-450b-917f-34f580f72bfd)

J'ai essayé divers navigateurs, même souci.

est ce que Digirisk utilise une librairie spéciale hors Dolibarr pour le tableau de la cotation avancée ?

Merci
Fred

### Environment Version

16.0.4

**Comment by lmag** [comment]
On va regarder pour la prochaine version

**Comment by nicolas-eoxia** [comment]
Après vérification il s'agit d'un bug provoquer par un module externe

La solution serait de modifier le problème dans le module en question ou de trouver un autre module plus a jour

**Comment by FredBl79** [comment]
> 

Bonjour Nicolas,

Merci pour l'investigation, afin de voir avec l'autre module, avez vous une piste à étudier pour le module externe qui ferait que l'affichage ne fonctionne plus ?

Merci
Fred

**Comment by nicolas-eoxia** [comment]
Bonjour @FredBl79,

J'ai vu avec Mr SILOBRE qu'il s'agissait du module timesheet
Je peux vous proposer d'utiliser le module DoliSIRH https://github.com/Evarisk/DoliSIRH qu'il fait la même chose en mieux

Bonne journée
Nicolas

**Comment by FredBl79** [comment]
> Bonjour @FredBl79,
> 
> J'ai vu avec Mr SILOBRE qu'il s'agissait du module timesheet Je peux vous proposer d'utiliser le module DoliSIRH https://github.com/Evarisk/DoliSIRH qu'il fait la même chose en mieux
> 
> Bonne journée Nicolas

Merci ;) j'ai déjà testé le module, celui que j'ai en prod actuellement répond mieux au besoin des utilisateurs.

Bonne journée
Fred
