### ISSUE TITLE
[Amélioration]-Proposition d'amélioration de la lecture de la cotation sur les risques simple

### ISSUE THREAD

**Issue by upecomsophie** [Evarisk/Digirisk#3149]
3765c01bb18f2180b983201bf235b6897a11ded4
**La description de la fonction attendue.**

![image](https://github.com/Evarisk/Digirisk/assets/39590601/41830ac9-732d-4f3b-95df-b0ade3a0ec40)

**Comment by lmag** [comment]
Super idée pour on va la planifier pour la prochaine version

**Comment by lmag** [comment]
Il faudra vérifier les bornes de notation
