### ISSUE TITLE
PROJECT_ADDON is null

### ISSUE THREAD

**Issue by lpadumorvan** [Evarisk/Digirisk#3165]
a fix avec saturne_require_object_mod

**Erreur au lancement du module**
Lorsque je clique sur l'icône Digirisk, j'obtiens une page blanche, ainsi qu'une erreur php dans les logs : 
 _Uncaught Error: Class name must be a valid object or a string in /var/www/html/dolibarr/htdocs/custom/digiriskdolibarr/digiriskdolibarrindex.php:60\nStack trace:\n#0 {main}\n  thrown in /var/www/html/dolibarr/htdocs/custom/digiriskdolibarr/digiriskdolibarrindex.php on line 60, referer: http://dolibarr.intranet.fr/htdocs/index.php?mainmenu=home&leftmenu=home_

Un `var_dump($conf->global->PROJECT_ADDON)` la ligne précedant la ligne en cause (`$projectRef  = new $conf->global->PROJECT_ADDON();`) renvoie NULL
Même erreur lorsqu'on essaie d'accéder à la page de configuration, avec le fichier /var/www/html/dolibarr/htdocs/custom/digiriskdolibarr/admin/setup.php (ligne 57). La ligne en cause est identique

**Configuration**
 - Dolibarr 16.0.5
 - Digirisk 9.10.0
 - CentOS 7
 - PHP 7.4.33

**Comment by nicolas-eoxia** [comment]
Bonjour, @lpadumorvan

Merci de votre participation

Cette issue sera corrigé dans la version 9.11
Voici le commit de correction : https://github.com/Evarisk/Digirisk/commit/540693b85a1ecbf6b0fe9c3f1dd276d1250b38d2

Bonne journée,

Nicolas

**Comment by lpadumorvan** [comment]
Merci de votre réponse rapide. j'ai appliqué le patch sur mon installation existante (9.10) et j'obtiens toujours une erreur. De fait `$conf->global->PROJECT_ADDON;` renvoie une valeur nulle (autour de la ligne 40 dans chaque fichier modifié) et le script échoue donc à inclure le fichier `require_once DOL_DOCUMENT_ROOT . '/core/modules/project/' . $projectRefClass . '.php';` quelques lignes plus loin
Le patch est-il applicable sur la 9.10 ou dois-je attendre la 9.11?
