### ISSUE TITLE
Modification de la présentation "action en cours" et "action terminées"

### ISSUE THREAD

**Issue by ocemag** [Evarisk/Digirisk#3211]
**La description de la fonction attendue.**
Il faut modifier la présentation des "actions en cours" et "actions terminées" en ajoutant des emojis.

**La description des données dont vous avez besoin**
![image](https://github.com/Evarisk/Digirisk/assets/41377034/9ecfadd9-1f1a-459b-a39c-c3986e1a106c)

**Les autres informations utiles**
Il faut modifier le DU et les listings de risques avec actions correctives.

**Comment by nicolas-eoxia** [comment]
enlever le texte barrée + texte action terminées + check homogénéité de la police
trouver l'origine de pourquoi this datecreation marche pas
