### ISSUE TITLE
Digirisk 9.13.0 et Saturne 1.1.2

### ISSUE THREAD

**Issue by FredBl79** [Evarisk/Digirisk#3509]
### Bug

Bonjour,

J'ai tenté de migrer en 9.13 et donc avec la librairie Saturne.

je suis confronté à pas mal de bugs et d'errors 500

Fatal error:  Uncaught Error: Call to undefined method SaturneTask::load_dashboard() in /var/www/newproto/htdocs/custom/digiriskdolibarr/class/digiriskdolibarrdashboard.class.php:83\

PHP Fatal error:  Uncaught Error: Class 'CustomModeleNumRefSaturne' not found in /var/www/newproto/htdocs/custom/digiriskdolibarr/core/modules/digiriskdolibarr/digiriskelement/groupment/mod_groupment_sirius.php

J'avoue avoir laissé tomber les recherches, est ce que j'utilise les mauvaises versions ? mais load_dashboard s'appelle LoadDashboard, la classe CustomModeleNumRefSaturne n'existe pas dans le code, il y en a une  ModeleNumRefSaturne

A suivre ....

### Environment Version

16.0.4

### Environment OS

Ubuntu

### Environment PHP

PHP 7

### Environment Database

MYSQL

**Comment by nicolas-eoxia** [comment]
Bonjour @FredBl79 

On viens de livrer la version de saturne 1.2.0 intégrant les bugs fix ainsi que le portage de digirisk 9.13.

Normalement, tout est fonctionnel si nécessaire tu peux me contacter pour régler les problèmes.

Bonne journée
Nicolas

**Comment by FredBl79** [comment]
> Bonjour @FredBl79
> 
> On viens de livrer la version de saturne 1.2.0 intégrant les bugs fix ainsi que le portage de digirisk 9.13.
> 
> Normalement, tout est fonctionnel si nécessaire tu peux me contacter pour régler les problèmes.
> 
> Bonne journée Nicolas

Bonjour @nicolas-eoxia ,

C'est parfait merci 👍
J'ai déployé cette version et tout fonctionne à présent.
Bravo pour le travail et bon devcamp!
