### ISSUE TITLE
not working after Update

### ISSUE THREAD

**Issue by dolibit-ut** [Evarisk/Digirisk#3511]
### Bug

I had Dolibarr 17.0.3 with SATURNE 1.1.2 and DGIRISK 9.10.0 and most of this worked fine.
Now I did an update to DIGIRISK 9.13.0  and after module reactivation and go to Setup or Menu
i get a blank page with this error:

Fatal error: Uncaught TypeError: Return value of SaturneObject::update() must be of the type int, null returned in C:\laragon\www\dolibarr-17\htdocs\custom\saturne\class\saturneobject.class.php:220 Stack trace: #0 C:\laragon\www\dolibarr-17\htdocs\custom\digiriskdolibarr\core\tpl\digiriskdolibarr_projectcreation_action.tpl.php(529): SaturneObject->update(Object(User)) #1 C:\laragon\www\dolibarr-17\htdocs\custom\digiriskdolibarr\digiriskdolibarrindex.php(33): require_once('C:\\laragon\\www\\...') #2 {main} thrown in C:\laragon\www\dolibarr-17\htdocs\custom\saturne\class\saturneobject.class.php on line 220

Menu Link:  localhost/dolibarr-17/htdocs/custom/digiriskdolibarr/digiriskdolibarrindex.php?idmenu=156&mainmenu=digiriskdolibarr&leftmenu=

### Environment Version

17.0.3

### Environment OS

Windows 10

### Environment Web server

Apache/2.4.35

### Environment PHP

7.4.27

### Environment Database

MariaDB 5.7.24

**Comment by dolibit-ut** [comment]
Now i have tried with Digirisk 9.12.0 instead of 9.13.0 and this works!

Maybe the older PHP version causes this problem?

**Comment by nicolas-eoxia** [comment]
Hello @dolibit-ut 

Thanks for the reporting.

Indeed we have update digirisk 9.13.0 with saturne 1.2.0 (https://github.com/Evarisk/saturne)
Recently.

This bug and other must be fix.
 
Have a good day.
Nicolas
