### ISSUE TITLE
Mise à l'echelle de la page 

### ISSUE THREAD

**Issue by btestaniere** [Evarisk/Digirisk#3517]
### Bug

Pas d'adaptation du texte du risque pour une mise à l'échelle de la page cad consultation du risque et de la tâche sans devoir redimensionner ou se déplacer sur la page.
Seule l'entité maitre à un bon comportement d'affichage.
![image](https://github.com/Evarisk/Digirisk/assets/49953190/57af7c74-005d-4ddb-9e3c-6e78a9491e91)
![image](https://github.com/Evarisk/Digirisk/assets/49953190/5dc1e128-33bc-4cc9-885e-6ccd50fe5cc0)

**Comment by evarisk-theo** [comment]
max width sur le composant 
entrée dans l'input va à la dernière ligne
