### ISSUE TITLE
[Amélioration] - Changement de la fiche d'UT de travail afin d'être plus lisible dans un atelier

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3532]
**La description de la fonction attendue.**

- [x] Ajout de l'unité séparément
- [x] Ajout des moyen de prévention avec une taille supérieur
- [x] Décalage des évaluateurs
- [x] Changement nom (établissement, registre santé sécurité etc...)
- [x] Dans les taches, simplifier les informations (Suppression réf tache, date, responsable, budget)
- [x] Reporter les informations sur les taches dans le Document Unique
- [x] Remplacer : Commentaire de l'évaluation -> Informations sur l'évaluation
- [x] Possibilité d'enlever la date sur l'information sur l'évaluation

Voir aussi l'issue : https://github.com/Evarisk/Digirisk/issues/3693

**Comment by nicolas-eoxia** [comment]
Modification a faire sur la fiche GP ou/et sur les listings également ?

**Comment by lmag** [comment]
Modification 1 demandée déjà réalisée dans la version 9.14.1
![image](https://github.com/Evarisk/Digirisk/assets/3288514/e8810db4-3b13-40d4-8ae7-232e46105893)
Modification 2 demandée
![image](https://github.com/Evarisk/Digirisk/assets/3288514/0165c94e-9f70-4afa-a24d-66e1f9a5baa8)
