### ISSUE TITLE
Workflow enquete accident a simplifier

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#3539]
Workflow actuel:

![Image](https://github.com/Evarisk/Digirisk/assets/111346550/8984fa0c-58db-4bc7-8e8a-393c8f1d19e7)

**Comment by evarisk-micka** [comment]
Proposition: 
Remplacer Versionner par Verrouiller (comme sur tous les objets) puisqu'il semblerait que ce soit le plus perturbant mais garder Nouvelle Version au lieu de Archiver (pour garder le processus de 1 version = 1 document)

![Image](https://github.com/Evarisk/Digirisk/assets/111346550/29cec64a-e94d-453a-8a8b-bce81b894752)
