### ISSUE TITLE
Erreur filtrage par unité GP dans listing de risques (risk_list.php)

### ISSUE THREAD

**Issue by titicopac** [Evarisk/Digirisk#3592]
### Bug

Impossibilité de rechercher par secteur dans le listing de risques.
![image](https://github.com/Evarisk/Digirisk/assets/100367004/6934944d-9ac7-42b8-813c-1d1f00e213ce)

**Comment by evarisk-francois** [comment]
Semble fonctionner sur la 19.0.1

**Comment by lmag** [comment]
C est ok
