### ISSUE TITLE
[Amélioration]-Mise à jour de l'ODT avec les nouveaux risques de l'INRS

### ISSUE THREAD

**Issue by AuroreBernard** [Evarisk/Digirisk#3648]
Manque 2 catégories et mise à jour des pictos

![image](https://github.com/Evarisk/Digirisk/assets/154441815/43f5568f-6cf4-468b-8fea-4a6fef16d3e5)

**Comment by lmag** [comment]
Merci Aurore pour cette remontée elle sera traitée lors de la prochaine version ! Il me semble que j'ai déjà traité une partie sur la branche developpement

**Comment by evarisk-micka** [comment]
Bonjour, cette issue a été réglé dans la prochaine version de Digirisk, merci pour votre retour.
