### ISSUE TITLE
Type de risque environnement - Catégories des risques

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3652]
Lister les types de risques selon les normes

- [ ] 140001 - ?

**Comment by 0000N** [comment]
"les conditions environnementales liées au climat, à la qualité de l’air, à l’utilisation du sol, à la
pollution existante, à la disponibilité de ressources naturelles et à la biodiversité, qui peuvent avoir
une incidence sur la finalité de l’organisme, ou être affectées par ses aspects environnementaux;"

Source ISO 14001 - A.4.1.a).

**Comment by lmag** [comment]
- [ ] Climat
- [ ] Qualité de l’air
- [ ] Eau
- [ ] Sol
- [ ] Nuisance
- [ ] Pollution existante
- [ ] Ressources naturelles
- [ ] Biodiversité

Permettre une description par type de risque dans la matrice avancée
- Eau (Fréquence, Gravité, Maitrise) récupérer les exemples

Une incidence sur la finalité de l’organisme, ou être affectées par ses aspects environnementaux

**Comment by SecuUrano** [comment]
Voir proposition faite dans "etablir les cotations des risques environnement" : 
- Consommation
- Emissions atmosphériques
- Effluents liquides
- Elimination de déchets
- Nuisances
- Sol / sous-sol
- Risques
A compléter avec la liste déjà ébauchée

**Comment by baptistehsedynamics** [comment]
![2024-02-26_22-29](https://github.com/Evarisk/Digirisk/assets/161015416/4875a827-ee66-46b9-8f7d-a2a53b32dee9)

**Comment by lmag** [comment]
Merci pour cette proposition, on ne peut pas avoir de risque nul ?

**Comment by baptistehsedynamics** [comment]
Si le risque est nul, il n'est pas envisagé dans l'analyse des aspects E.
La cote à 0 peut être justifiée par le fait d'avoir pris en compte toutes les situations devant un auditeur, mais elle alourdit la lecture de l'analyse et le projet associé.

**Comment by lmag** [comment]
OK ? @SecuUrano 
On pourrait aussi archiver un risque traité

**Comment by lhalfaoui** [comment]
Bonjour, 
C'est d'accord pour le principe.

**Comment by baptistehsedynamics** [comment]
Proposition de catégories d’aspects environnementaux qui seront représentées à la manière des risques actuels 

- AIR : Émissions ( polluants, vapeur, CO2)
- EAU : Rejets 
- SOL : Rejets 
- RESSOURCES : consommation  
- VOISINAGE : ( chaleur, rayonnement, vibrations, lumière) 
- DÉCHETS : production

![2024-03-04_15-22](https://github.com/Evarisk/Digirisk/assets/161015416/3ffdf85a-1fc6-4a5d-9143-6640ec105d77)

Définition de la gravité des aspects par catégorie : emplacement à déterminer

AIR : Pas d'impact / Nocivité faible rejets conformes /Nocivité modérée rejets traités non conformes / Nocivité importante: rejets polluants / Nocivité majeure : rejets très polluants

EAU : Pas d'impact / Nocivité faible rejets conformes / Nocivité modérée rejets non conformes après traitement PH acide/basique / Nocivité forte rejets polluants : chlore / Nocivité  majeure rejets très polluants : métaux lourds

SOL : Pas de déversement / Déversement de matières dangereuses en faibles quantités (bidons) / Déversement de matières dangereuses en quantités modérées (fûts) / Déversement de matières dangereuses en fortes quantités (citernes <1000l ) / Déversement de matières dangereuse en très forte quantité ( cuves > 1000l ) 

RESSOURCES  : Pas de consommation / Ressources faiblement consommées ou recyclées / Ressources moyennement consommées ou partiellement recyclables/ Ressources fortement consommées non recyclables / Ressources gaspillées ou rares

VOISINAGE : Absence d'impact / Impact faible :  faibles nuisances contenues à proximité de l'activité / Impact moyen : nuisances moyennes à proximité de l'activité / Impact fort : nuisances sur tout le site / Impact majeur :  nuisances impactant l'extérieur du site.

DÉCHETS :  Absence de déchets / Déchets recyclés, triés /  production moyenne de DD / production important de DD / production massive de DD

**Comment by SecuUrano** [comment]
Validé de mon côté, ça me parait très bien présenté comme ça

**Comment by lmag** [comment]
Picto à faire : 

- [ ] AIR : Pas d'impact / Nocivité faible rejets conformes /Nocivité modérée rejets traités non conformes / Nocivité importante: rejets polluants / Nocivité majeure : rejets très polluants
- [ ] EAU : Pas d'impact / Nocivité faible rejets conformes / Nocivité modérée rejets non conformes après traitement PH acide/basique / Nocivité forte rejets polluants : chlore / Nocivité majeure rejets très polluants : métaux lourds
- [ ] SOL : Pas de déversement / Déversement de matières dangereuses en faibles quantités (bidons) / Déversement de matières dangereuses en quantités modérées (fûts) / Déversement de matières dangereuses en fortes quantités (citernes <1000l ) / Déversement de matières dangereuse en très forte quantité ( cuves > 1000l )
- [ ] RESSOURCES : Pas de consommation / Ressources faiblement consommées ou recyclées / Ressources moyennement consommées ou partiellement recyclables/ Ressources fortement consommées non recyclables / Ressources gaspillées ou rares
- [ ] VOISINAGE : Absence d'impact / Impact faible : faibles nuisances contenues à proximité de l'activité / Impact moyen : nuisances moyennes à proximité de l'activité / Impact fort : nuisances sur tout le site / Impact majeur : nuisances impactant l'extérieur du site.
- [ ] DÉCHETS : Absence de déchets / Déchets recyclés, triés / production moyenne de DD / production important de DD / production massive de DD
- [ ] DIVERS :

**Comment by evarisk-martin34** [comment]
![image](https://github.com/Evarisk/Digirisk/assets/105202836/b45e955f-6d10-420b-a01d-eb8157335b2a)
Premiers jets

**Comment by baptistehsedynamics** [comment]
Pour consommations, on parle des consommation de matières premières et de ressources naturelles je verrais bien un arbre, une roche et de l'eau par exemple.
Pour les déchets je choisirais plutôt des déchets indus bien que tous les déchets sont concernés.

**Comment by lmag** [comment]
Effectivement je suis plutôt d'accord, n'hésites pas à en discuter avec @eoxia-amandine et a garde un style homogène.

**Comment by evarisk-martin34** [comment]
![image](https://github.com/Evarisk/Digirisk/assets/105202836/28ee015f-a9da-406a-86b8-dd70ffcffbd1)
Corrections en fonction des retours 
Je demande à Amandine pour l'homogénéité

**Comment by baptistehsedynamics** [comment]
Parfait

**Comment by evarisk-martin34** [comment]
![image](https://github.com/Evarisk/Digirisk/assets/105202836/c18a6b78-ad7b-4438-9aea-9b77fa90d151)
Autre proposition après discussion weekly

**Comment by SecuUrano** [comment]
La première version est bien

**Comment by SecuUrano** [comment]
2ème*

**Comment by lmag** [comment]
Attention : Modification liée à la lecture de l'annexe A 6.1.2 de l'ISO 140001
a) les émissions dans l’air;
b) les rejets dans l’eau;
c) les rejets dans le sol;
d) l’utilisation des matières premières et des ressources naturelles;
e) l’utilisation de l’énergie;
f) l’énergie émise (par exemple chaleur, rayonnement, vibrations (bruit), lumière);
g) la production de déchets et/ou de sous-produits;
h) l’utilisation de l’espace.
i) Divers risques environnementaux "ajout de DigiRisk"
Utiliser la référence dans le chapitre pour justifier les catégories

**Comment by lmag** [comment]
@MartinHennes @SecuUrano @baptistehsedynamics

**Comment by evarisk-martin34** [comment]
@lmag 
a) les émissions dans l’air; - Cheminée usine
b) les rejets dans l’eau; - Egoulement eau sale usine
c) les rejets dans le sol; Polution nappe au sol
d) l’utilisation des matières premières et des ressources naturelles; (Arbre eau cailloux)
e) l’utilisation de l’énergie; (Energivore ? Voir Discord)
f) l’énergie émise (par exemple chaleur, rayonnement, vibrations (bruit), lumière);
g) la production de déchets et/ou de sous-produits; Voir DIB
h) l’utilisation de l’espace. Voir la norme pour la définition "espace"
i) Divers risques environnementaux "ajout de DigiRisk" voir Discord

Il faudrait un pictogramme pour chacune de ces lignes ?

**Comment by lmag** [comment]
Peux-tu aussi faire une illustration pour les risques environnementaux en prenant le style suivant avec 2 axes visibles:

- Le Risque
- L'opportunité

![Image](https://github.com/Evarisk/Digirisk/assets/3288514/6a648deb-5cf7-4b55-9cac-243cde8b4761)
@MartinHennes

**Comment by evarisk-martin34** [comment]
Suppression du cercle blanc

![Pictogrammes utilisation_energie](https://github.com/Evarisk/Digirisk/assets/105202836/6342f43b-242f-4862-b28e-1b23d3fc406d)

Mettre les couleurs et pointer vers le Rouge
![image](https://github.com/Evarisk/Digirisk/assets/3288514/45f1962e-a91e-4411-921b-2e5c77be3894)


![Pictogrammes environnement_divers](https://github.com/Evarisk/Digirisk/assets/105202836/ec08e309-0d1a-4a2d-8a8b-9f041dd72468)
C'est un picto d'améliorations continuent les flèches c'est un message confus
![Pictogrammes environnement_energie_emise](https://github.com/Evarisk/Digirisk/assets/105202836/95dc379d-1af6-4055-80c2-0acb4e2af33f)

![Pictogrammes environnement_matieres_premieres](https://github.com/Evarisk/Digirisk/assets/105202836/abd432b6-bdf9-408f-9f70-b4b8d3044a15)
Intégration des couleurs notamment pour l'arbre

![Pictogrammes environnement_production_dechets](https://github.com/Evarisk/Digirisk/assets/105202836/bc671089-e2b7-432e-87f2-94181a7dac8e)

Améliorer la visibilité du recyclage

![Pictogrammes environnement_rejets_air](https://github.com/Evarisk/Digirisk/assets/105202836/a101c0fe-fa0a-4587-be72-f37e829974b7)

![Pictogrammes environnement_rejets_eau](https://github.com/Evarisk/Digirisk/assets/105202836/c4a285eb-bbe6-4921-9e52-428a307ecd42)

![Pictogrammes environnement_rejets_sol](https://github.com/Evarisk/Digirisk/assets/105202836/4d034543-e710-4d44-bd47-2364da1137cc)

Pénétration dans le sol doit être un peu lisible (pour un picto)

![Pictogrammes environnement_utilisation_espace](https://github.com/Evarisk/Digirisk/assets/105202836/58e8c42a-0936-4bb2-9f14-99e406d56adc)

**Comment by evarisk-martin34** [comment]
Corrections 
![image](https://github.com/Evarisk/Digirisk/assets/105202836/00b6dfbc-ce39-4c64-b05e-903280b17750)

Propositions logo divers risques environementaux
![image](https://github.com/Evarisk/Digirisk/assets/105202836/28da3b8d-4599-4e04-a181-9647e378d330)

**Comment by baptistehsedynamics** [comment]
Ok c'est beaucoup plus compréhensible et il y aura la description de l'impact E par contre je respecterais les couleurs de la cotation énergétique.
Pour l'espace, au sens de la norme je pense qu'il s'agit de l'espace cosmologique.
Pour le logo divers, je choisirais celui-ci 
![image](https://github.com/Evarisk/Digirisk/assets/161015416/fb2a551e-969c-4802-8df9-c21cd6d31691)
