### ISSUE TITLE
[Bug] "Déplacer les risques" la liste des GP et UT n'apparait pas

### ISSUE THREAD

**Issue by 0000N** [Evarisk/Digirisk#3655]
Bonjour, 

**`Même si l'option "Déplacer les risques" est activée (Cf. image ci-dessous) :`**

![image](https://github.com/Evarisk/Digirisk/assets/115844632/dfef1e20-25f7-490d-9403-3dd01a524f26)

**`Dans la liste du groupement ou de l'unité de travail, apparait que le nom de la racine, tous les autres groupements et unités n'apparaissent pas :`** 

![Screenshot 2024-01-16 at 16-29-25 Unité de travail multicompany](https://github.com/Evarisk/Digirisk/assets/115844632/f24367d9-18a7-40ad-8d9e-9db08a762bdf)

**Comment by lmag** [comment]
Il me semble que l'issue est en doublon
Planification ok

**Comment by evarisk-micka** [comment]
Merci pour la remontée de cette issue.
Le problème n'est plus présent dans la version 9.14.1 qui arrive prochainement ! #3659
