### ISSUE TITLE
DIGIRISK - Document Unique - Dupliquer groupement, unité de travail et risque

### ISSUE THREAD

**Issue by lvourey** [Evarisk/Digirisk#3668]
Bonjour.
Dans le cadre de l'acquisition d'un nouveau site, je souhaiterais créer un nouveau groupe et dupliquer l'arborescence d'un groupe existant, avec les unités de travail et les risques associés.

J'ai bien l'option de déplacement de risque activée mais pas la possibilité de les dupliquer.
Autrement dit, lorsque je déplace un risque, il n'apparait plus dans son unité initiale.

Comment faire pour recréer l'arborescence sans recréer chaque risque un par un?

Merci pour votre aide.

**Comment by evarisk-micka** [comment]
Bonjour, il n'existe aujourd'hui pas de moyen de copier coller une arborescence entière avec les risques dupliqués à l'intérieur.
Néanmoins vous soulevez une fonctionnalité intéressante et nous étudierons la question sous peu.
Merci pour votre retour !

**Comment by lmag** [comment]
En fonction de vos usages, vous pourriez utiliser la fonction d'export et d'import dans les outils. Il existe aussi la notion de risque hérités et surtout partager qui vous permet de gerer des bibliothèques de risques (Je vous conseil de lire la documentation à ce sujet)
