### ISSUE TITLE
[BUG] problème de duplication de insert SQL dans config événements 

### ISSUE THREAD

**Issue by evarisk-charles** [Evarisk/Digirisk#3684]
### Bug

problème de duplication de insert SQL dans config événements 
![image](https://github.com/Evarisk/Digirisk/assets/158461084/a8c69546-01a4-4b4b-9197-7e172c0287ea)
![image](https://github.com/Evarisk/Digirisk/assets/158461084/00bc9c0f-8977-4540-a343-568af9e79ffe)
![image](https://github.com/Evarisk/Digirisk/assets/158461084/84f78a54-c7b9-46b1-9a0d-5751b706fc53)

### Environment Version

18.0.0

**Comment by evarisk-micka** [comment]
Backward tout delete avant de reinsert
