### ISSUE TITLE
[Amélioration] -IHM Unité de travail simplifiée

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3693]
Penser à modifier les tableaux de chaque template document
-----

Mise en place des sauts de ligne sur les tableaux avec répétition du titre

Exemple de la nouvelle fiche
![image](https://github.com/Evarisk/Digirisk/assets/3288514/0a7c3f65-4f02-48c5-8d71-cd208cf3d517)

2ieme page
![image](https://github.com/Evarisk/Digirisk/assets/3288514/8ae3a969-8fb1-4797-b69b-9753509bf2b6)

**Comment by lmag** [comment]
Voir l'issue
https://github.com/Evarisk/Digirisk/issues/3693
Nouvelle proposition
![image](https://github.com/Evarisk/Digirisk/assets/3288514/f0438a5b-d165-4028-9f27-6b3bdda432b4)

**Comment by lmag** [comment]
![image](https://github.com/Evarisk/Digirisk/assets/3288514/14ae0c8e-f4a6-44b9-8af2-0706523c5370)
[20240214_WU14_WUD73_Entreprise.odt](https://github.com/Evarisk/Digirisk/files/14279779/20240214_WU14_WUD73_Entreprise.odt)

**Comment by nicolas-eoxia** [comment]
Alors, après review, il y a plusieurs problème a voir @evarisk-micka

**Comment by evarisk-micka** [comment]
Le tableau des signalisations n'était pas bien formaté
