### ISSUE TITLE
[Amélioration] Les tickets n'apparaissent pas le document généré UT

### ISSUE THREAD

**Issue by lhalfaoui** [Evarisk/Digirisk#3715]
Bonjour, 

Les tickets n’apparaissent pas dans les documents générés : 

![image](https://github.com/Evarisk/Digirisk/assets/161040175/5a5ac06f-c638-410f-bdea-81e830041120)

Cordialement,

**Comment by lhalfaoui** [comment]
Bonjour, 
Je me permets de revenir sur cette issue, car maintenant il y a trop de tickets.
Les tickets qui ne sont pas liés à un GP/UT apparaissent également. 

Certains tickets en lien avec de la qualité pure n'ont pas leur place dans l'export du DU. 

Un filtre dans ce sens peut être mis en place ?

Cordialement,

**Comment by nicolas-eoxia** [comment]
Je viens de créer une issue dans le projet 10.1.1 : https://github.com/Evarisk/Digirisk/issues/3923
