### ISSUE TITLE
Suppression de la phrase en double lors de la notification des tickets

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3720]
La notification envoie la phrase suivante 

![Image](https://github.com/Evarisk/Digirisk/assets/3288514/bf37ed40-1991-4fae-9e7f-437b1eb89ba6)

Meme si on la supprime de la configuration

**Comment by evarisk-micka** [comment]
[#30010](https://github.com/Dolibarr/dolibarr/issues/30010)

https://github.com/Dolibarr/dolibarr/pull/30081
