### ISSUE TITLE
 Tableau de bord général -  Ajout du nombre de GP Enfant

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3781]
Information sur le GP enfant

- [x] Ajout du nombre de GP Enfants

![Image](https://github.com/Evarisk/Digirisk/assets/3288514/d36ace2f-8803-47a5-aafd-561574afc605)

- [x] Ajout du nombre de risque cumulé par GP enfant
- [ ] Ajout possible du niveau des risques par cotation en plus à droite (Gris, Orange, Rouge, Noir) non présent dans la copie d'écran

![Image](https://github.com/Evarisk/Digirisk/assets/3288514/5622f256-988b-430f-aa31-38eb4d1d082c)

- [x] Ajout des risques par famille de risque et niveaux de cotation

![Image](https://github.com/Evarisk/Digirisk/assets/3288514/699281da-4171-421d-8ad2-bff7ed62abb2)

**Comment by nicolas-eoxia** [comment]
c'est la somme des cotations mais on fera aussi pour la somme des nb de cotations

**Comment by lmag** [comment]
![Image](https://github.com/Evarisk/Digirisk/assets/3288514/a07f326e-617b-45b5-9e6c-985a498ee04a)
Export en CSV
OK
![Image](https://github.com/Evarisk/Digirisk/assets/3288514/da531cf3-45e2-4d3a-9679-f1840cb88d9a)
OK - Avec une transposé et les titres dans le CSV

- [ ] Changement texte "Répartition de l'arborescence des groupements de niveau X"
