### ISSUE TITLE
BUG programme line 875

### ISSUE THREAD

**Issue by TTlephant** [Evarisk/Digirisk#3823]
### Bug

Bonjour, quand j'essaye de rajouter digirisk à Dolibarr dans le dossier custom il me renvoie ça :
Fatal error: Uncaught Error: Call to undefined function isModEnabled() in C:\dolibarr\www\dolibarr\htdocs\custom\Digirisk-main\core\modules\modDigiriskDolibarr.class.php:875 Stack trace: #0 C:\dolibarr\www\dolibarr\htdocs\admin\modules.php(341): modDigiriskdolibarr->__construct(Object(DoliDBMysqli)) #1 {main} thrown in C:\dolibarr\www\dolibarr\htdocs\custom\Digirisk-main\core\modules\modDigiriskDolibarr.class.php on line 875
Si je comprend bien, il ne connait pas la fonction isModEnabled si vous avez des idée je suis preneur.
Merci

PS : j'ai utilisé tout les document et exécutable fourni dans le mail d'envoie de demande de digirisk et le code fourni sur github pour essaye de résoudre le problème qui est le même.

### Environment Version

14.0.5

### Environment OS

Windows 10 64 bit

**Comment by evarisk-micka** [comment]
Bonjour,

Le problème vient de la version de votre instance Dolibarr qui est en version 14.0.1
Voici un lien vers une version plus récente contenant les fonctions manquantes que nous utilisons dans nos modules => https://sourceforge.net/projects/dolibarr/files/Dolibarr%20installer%20for%20Windows%20%28DoliWamp%29/19.0.1/

Assurez-vous également d'utiliser la dernière version de notre module Digirisk => https://github.com/Evarisk/Digirisk/releases/tag/9.15.0
Et la dernière version de notre module Saturne => https://github.com/Evarisk/Saturne/releases/tag/1.3.0

Cordialement,

L'équipe technique Evarisk.
