### ISSUE TITLE
[Amélioration] Permis de feu - ronde post travaux (2h)

### ISSUE THREAD

**Issue by lhalfaoui** [Evarisk/Digirisk#3854]
Bonjour, 

Dans le permis feu, ajouter un responsable pour **réaliser une rode post travaux** : 
=> Ajouter une alerte en fonction de la fin des travaux ? 
=> Ajouter possibilité de faire une photo ?
**=> Enfin, ajouter une signature après la ronde**

Cordialement,

**Comment by lmag** [comment]
Mais on dirait un simple contrôle qualité à faire avec DigiQuali non ?

**Comment by lhalfaoui** [comment]
Effectivement, mais pour être sûr que ce soit efficace, il serait judicieux de générer un contrôle automatiquement dès la création d'un permis feu.

**Comment by lmag** [comment]
à suivre ici : 
https://github.com/Evarisk/DigiQuali/issues/488
https://github.com/Evarisk/DigiQuali/issues/1795

**Comment by lmag** [comment]
@lhalfaoui il reste à faire le premier controle pour un permis de feu :) bientot sur demo.digirisk.com

**Comment by lhalfaoui** [comment]
Dès que la mise à jour est installée sur la demo je reviens vers vous.
