### ISSUE TITLE
Erreur dans les dates sur la rapport d'audit

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3863]
### Bug
Les dates ne sont pas les bonnes dans le rapport d'audit

![image](https://github.com/Evarisk/Digirisk/assets/3288514/5943b06e-6a22-4b41-bffe-2cb9a8f5913f)

### Environment Version

19.0.1

**Comment by nicolas-eoxia** [comment]
Il ne s'agit pas d'une erreur la plage de date est utilisé pour faire une recherche entre deux dates mais les données de génération du document pour la page de garde provienne de la page document unique
