### ISSUE TITLE
Les tâches des risques partagés ne descendent pas quand on partage le risque depuis le DUER générique

### ISSUE THREAD

**Issue by CoralieBx** [Evarisk/Digirisk#3895]
### Bug

Les taches des risques partagés n'apparaissent pas sur le site enfant.
![image](https://github.com/Evarisk/Digirisk/assets/109144265/4256cfd4-f8fd-4441-a2f6-b4dc25c4b20e)

**Comment by nicolas-eoxia** [comment]
Bonjour @CoralieBx ,

Merci de votre participation

J'ai vérifié votre instance , il n'y a pas de problème apparent sur ça.
En effet, la configuration des projet partagés et le lien entre l'entité maitre et fille est réalisé.
Dans la capture d'écran si dessus, vous m'avez indiqué un risque avec aucune tâche en cours 
S'il la tâche n'est pas partagé il y aurait écrit "pas de tâches partagées"

N'hésiter pas à revenir vers moi, si c'est pas clair ou si le problème persiste

Bonne journée,

Nicolas
