### ISSUE TITLE
bug reload js lors de la création d'un risque

### ISSUE THREAD

**Issue by evarisk-charles** [Evarisk/Digirisk#3900]
![Image](https://github.com/Evarisk/Digirisk/assets/158461084/9493ccd3-a9c8-480d-ab6f-ceaffdf30bc1)

**Comment by evarisk-francois** [comment]
Surement un bug sur les versions précédentes, je ne peux pas reproduire l'erreur en 19.0.1 et 19.0.2.

**Comment by nicolas-eoxia** [comment]
Le bug apparait lors de l'ajout d'un risque sur une configuration ou il y a les risques partagées
