### ISSUE TITLE
Statistique - Liste des risques par catégorie de danger

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3913]
![Image](https://github.com/Evarisk/Digirisk/assets/3288514/22eb13f4-181a-425a-9976-9cfb97a070fc)

Erreur dans la somme : 13+ 2+ 4 = 19 et pas 20

**Comment by nicolas-eoxia** [comment]
Cause fk_element = 0 (sensé être impossible)
a voir si je clean pas la bdd ou si je fais un check sur la requete
