### ISSUE TITLE
Il ne prend pas toujours en compte les couleurs sur les tickets dans les statistiques

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3915]
### Bug

![image](https://github.com/Evarisk/Digirisk/assets/3288514/356f22a6-ceef-4c57-82f7-56468da0b9f7)

![image](https://github.com/Evarisk/Digirisk/assets/3288514/70ebbece-a762-4d7c-8604-33d2615f08d9)

**Comment by evarisk-micka** [comment]
Possiblement réparé par [#943](https://github.com/Evarisk/Saturne/issues/943)
