### ISSUE TITLE
Filtre non actif sur le listing des risques - Attention à la pagination 500 risques par page

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3916]
### Bug

Voir commentaires

![image](https://github.com/Evarisk/Digirisk/assets/3288514/f563ece1-842a-4758-b441-67a28b901489)

**Comment by evarisk-micka** [comment]
Si trop de risques la recherche par REF ne fonctionne pas
Si dans une autre page, ça ne fonctionne pas aussi

**Comment by evarisk-micka** [comment]
Sera corrigé par [#950](https://github.com/Evarisk/Saturne/issues/950)
