### ISSUE TITLE
Erreur de catégorie "-1" sortir un listing

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#3917]
### Bug

Sortir les risques qui n'ont pas de catégorie
![image](https://github.com/Evarisk/Digirisk/assets/3288514/4ec0b097-b7be-4f52-a385-de6bb723afd2)

- [ ] Permettre la réparation
- [ ] Permettre de voir les risques concernés

**Comment by evarisk-micka** [comment]
Ajouter un outil permettant de réparer les risques sans catégories
