### ISSUE TITLE
[Amélioration] DU  - > Tableau ticket afficher les tickets qui ont un lien sur un GP/UT

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/Digirisk#3923]

**Comment by nicolas-eoxia** [comment]
Bonjour @0000N,

Actuellement nous affichons tous les tickets du projet TS - NomSociete.
Est-ce que cela te semble une bonne proposition ?

**Comment by lhalfaoui** [comment]
Bonjour, 
Pour le projet, c'est bon.
C'est surtout à l'impression du **Document Unique** qu'il serait judicieux d'appliquer un filtre GP/UT.

**Comment by nicolas-eoxia** [comment]
Bonjour @lhalfaoui,

Oui, nous allons appliquer sur les ticket ticket qui ont un lien sur un GP/UT + dans le projet TS.
