### ISSUE TITLE
[Amélioration]-permettre l'envoi du plan de prévention à l'entreprise extérieure

### ISSUE THREAD

**Issue by EmmaVenot** [Evarisk/Digirisk#3937]

**Comment by lmag** [comment]
Merci pour cette demande en effet l'envoi des Emails ne propose que l'inspection du travail

- [x] Ajouter le tiers
- [x] Ajouter les contacts

![image](https://github.com/Evarisk/Digirisk/assets/3288514/e103e1da-56dc-467f-86e9-f64fda250642)
![image](https://github.com/Evarisk/Digirisk/assets/3288514/ac6d717b-489a-42ba-9c90-52fb958bdab9)
