### ISSUE TITLE
Fatal error :  digiriskdolibarr_projectcreation_action.tpl.php 

### ISSUE THREAD

**Issue by VRivereau** [Evarisk/Digirisk#3980]
Bonjour, 

Suite à installation de la version 10.2.0 en cliquant sur l'icône DIGIRISK dans le menu du haut, j'obtiens une page blanche "erreur 500". 
notre configuration : DOLIBARR : 19.0.2 SATURNE : 1.5.0 

Voir ci-dessous le détail des logs.
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  require_once(/var/www/html/custom/digiriskdolibarr/core/tpl/digiriskdolibarr_projectcreation_action.tpl.php): Failed to open stream: No such file or directory in /var/www/html/custom/digiriskdolibarr/digiriskdolibarrindex.php on line 33",
{"@type":"error_log","@app":"digirisk","message":"PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/custom/digiriskdolibarr/core/tpl/digiriskdolibarr_projectcreation_action.tpl.php' (include_path='/var/www/html/htdocs') in /var/www/html/custom/digiriskdolibarr/digiriskdolibarrindex.php:33\nStack trace:\n#0 {main}\n  thrown in /var/www/html/custom/digiriskdolibarr/digiriskdolibarrindex.php on line 33",}
{"@type":"access_log","@app":"digirisk","message":"GET /custom/digiriskdolibarr/digiriskdolibarrindex.php?idmenu=301&mainmenu=digiriskdolibarr&leftmenu= HTTP/1.1","statut":"500","temps":"117400","taille":"304",}

Cdlt,

**Comment by nicolas-eoxia** [comment]
Bonjour @VRivereau,

Je n'arrive pas à reproduire le problème que vous rencontré.
Pouvez-vous m'envoyer une capture d'écran complète de l'erreur fatale ?

Nicolas
