### ISSUE TITLE
Anomalies dans la remonté des chiffres dans le tableau de bord

### ISSUE THREAD

**Issue by ThomasSHS** [Evarisk/Digirisk#4049]
### Bug

Les chiffres qui sont remontés dans le tableau de bords sont faux et tous différents. Cela concerne les catégories suivantes : Répartition des risques par évaluation, liste des risques par catégorie de danger mais aussi la liste des risques.

### Attached files

![Liste des risques](https://github.com/user-attachments/assets/2f269495-c1e7-4116-90c8-8f15fe996e09)
Cela semble être le plus proche de la réalité même si le total du nombre de risque obtenue lors de l'addition manuelle des groupements est de 2229 au lieu de 2784.

![Anomalie Répartition des risques par évaluation](https://github.com/user-attachments/assets/5321bd4f-0529-4bd6-906e-77859f555a22)
Le total de la répartition des risques nous donne un premier chiffre différent.
Aussi il est indiqué 3 risques inacceptables, alors qu'aucun n'apparaît dans la liste de risque et un seul apparaît dans la répartition des catégories de danger (ci-dessous).

![Anomalie Liste des risques par catégorie de danger](https://github.com/user-attachments/assets/aa8982f4-4531-49ad-a1db-e2cebda712d9)
Au delà du total différent des cas cités ci-dessus, nous avons également une anomalie dans la répartition. L'addition des chiffres après répartition donne 4126 au lieu de 4868.
Et si nous nous concentrons sur la première ligne nous pouvons déjà constater que la répartition du risque "Chute de plain-pied" est différente du total pour le même risque.

**Comment by lmag** [comment]
Duplicate : https://github.com/Evarisk/Digirisk/issues/4067
