### ISSUE TITLE
[Amélioration] Les chiffres remontés dans le tableau de bord sont incorrect

### ISSUE THREAD

**Issue by ThomasSHS** [Evarisk/Digirisk#4067]
Les chiffres qui sont remontés dans le tableau de bords sont incorrect et tous différents. Cela concerne les catégories suivantes : Répartition des risques par évaluation, liste des risques par catégorie de danger mais aussi la liste des risques.

![image](https://github.com/user-attachments/assets/80d9ffc4-dbd3-4c09-abb0-e0393e018e05)
Cela semble être le plus proche de la réalité même si le total du nombre de risque obtenue lors de l'addition manuelle des groupements est de 2229 au lieu de 2784.

![image](https://github.com/user-attachments/assets/3e8dc316-4733-4e08-a068-79be45007bbc)
Le total de la répartition des risques nous donne un premier chiffre différent.
Aussi il est indiqué 3 risques inacceptables, alors qu'aucun n'apparaît dans la liste de risque et un seul apparaît dans la répartition des catégories de danger (ci-dessous).

![image](https://github.com/user-attachments/assets/548eab08-850c-4c80-93e0-d80f9bf762b2)
Au delà du total différent des cas cités ci-dessus, nous avons également une anomalie dans la répartition. L'addition des chiffres après répartition donne 4126 au lieu de 4868.
Et si nous nous concentrons sur la première ligne nous pouvons déjà constater que la répartition du risque "Chute de plain-pied" est différente du total pour le même risque.

Est-il possible de vérifier pourquoi nous avons ces incohérences et de les corriger ?
Merci par avance pour votre travail

**Comment by lmag** [comment]
**Actions curatives**
- [ ] Contrôle des bases de données avec des risques supprimés et réaffectés -> Création d'un outil de réparation
- [x] Contrôle des évaluations qui n'ont pas cotation "Cotation nulle" -> Création outils https://github.com/Evarisk/Digirisk/issues/4069
- [x] Contrôle des risques sans affectation : https://github.com/Evarisk/Digirisk/issues/4068
- [x] Contrôle des risques sans cotation (Il existe des risques sans cotation lors de l'import)
- [ ] Contrôle des requêtes sur les fichiers *.odt

**Actions préventives**
- [ ] Centralisation des requêtes identiques
- [ ] Contrôle des requêtes de risque

**Comment by nicolas-eoxia** [comment]
![image](https://github.com/user-attachments/assets/89068eae-4faa-40ec-8117-79b4859d2126)

**Comment by lmag** [comment]
![image](https://github.com/user-attachments/assets/f2bee038-0217-4ff3-8d3a-9e2126fb9d77)

**Comment by lmag** [comment]
![image](https://github.com/user-attachments/assets/85904af7-71c9-4173-aa1e-3eaace6484c0)

**Comment by lmag** [comment]
![image](https://github.com/user-attachments/assets/d654c326-1192-4ac7-8f29-122e00131cc4)

**Comment by lmag** [comment]
Correction réalisée
![image](https://github.com/user-attachments/assets/8db514a4-23f3-40ad-9c4b-9352733a02f9)

**Comment by lmag** [comment]
Correction ok sur le listing
![image](https://github.com/user-attachments/assets/5136e987-0240-4fa1-a5b2-388fb02d00b0)
