### ISSUE TITLE
[Amélioration] Tableau de bord risques inacceptables

### ISSUE THREAD

**Issue by lhalfaoui** [Evarisk/Digirisk#4073]
Bonjour, 

Les risques "inacceptables" ne sont pas repris dans le tableau de bord :  

![image](https://github.com/user-attachments/assets/e9ce0f49-0a3b-4c07-b1fa-89fc01113b9f)
![image](https://github.com/user-attachments/assets/5988509c-e57e-4fe5-b5a1-2a444032f600)

**Comment by nicolas-eoxia** [comment]
Fix dans la version 10.3.0
