### ISSUE TITLE
[Amélioration] Tickets - édition des champs du formulaire (Attributs)

### ISSUE THREAD

**Issue by lhalfaoui** [Evarisk/Digirisk#4078]
Bonjour, 

Est-ce possible de personnaliser ces champs sur le formulaire de ticket ?
Par exemple : ajouter le mail du pilote, estimer un budget, ... etc. 

![image](https://github.com/user-attachments/assets/c1ad6107-c833-40b8-8270-26c3a1bb6bdc)

**Comment by lmag** [comment]
Bonjour,  @lhalfaoui 
Dans la nouvelle version de DigiRisk qui est en cours de finalisation nous avons intégré : (https://github.com/orgs/Evarisk/projects/131)
Ajout des informations basé sur le tag afin de prédéfinir un WorkFlow :
**1. Pilote (utilisateur que l'on va informer
2. Mail dédié par TAG**

En installant, EasyCRM, on obtient 

**1. La possibilité d'ajouter une tâche sur un ticket
2. D'affecter DU temps relié au ticket grâce à la tâche
3. D'affecter un budget lié à cette tâche**

Nous avons en projet l'amélioration des tickets afin de simplifier l'ajout des taches, du temps et des responsables.

**Comment by lmag** [comment]
@lhalfaoui Vous aurez toutes ces fonctions dans la version 10.3 et 10.4
