### ISSUE TITLE
[Amélioration] Ajout heure minute dans la colonne des évènements des tickets dans le modèle ODT

### ISSUE THREAD

**Issue by PerrineSICTOM** [Evarisk/Digirisk#4089]
![image](https://github.com/user-attachments/assets/1690e5eb-7d58-42d4-86c8-5472c6a07481)

**Comment by nicolas-eoxia** [comment]
Bonjour, @PerrineSICTOM

Merci de votre participation

Cette issue sera corrigé dans la version 10.3.0
Voici le lien vers le suivi de l'issue : https://github.com/Evarisk/Digirisk/pull/4129

Bonne journée,

Nicolas
