### ISSUE TITLE
[Amélioration] Classement par niveau de risque - prise en compte évaluation et réévaluation

### ISSUE THREAD

**Issue by lhalfaoui** [Evarisk/Digirisk#4097]
Bonjour, 
Dans la liste des risques, le classement par niveau de risque, se base à priori que sur la première évaluation : 

**Liste des évaluations :** 

![image](https://github.com/user-attachments/assets/ef5df8fb-327a-4f5f-870a-657b14d0d2ae)

**Classement par niveau de risque :** 

![image](https://github.com/user-attachments/assets/5e83ed46-074c-47c7-a599-d8163d70597b)

**Comment by lmag** [comment]
Bonjour, 
On n'arrive pas a reproduire sur la demo avez vous recharger la page ? car la ligne reste en place

**Comment by lhalfaoui** [comment]
Bonjour, 
Oui j'avais rechargé.
Maintenant c'est fonctionnel, donc tout va bien.
