### ISSUE TITLE
[Amélioration] - Tableau de bord Document Unique

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#4105]
**La description de la fonction attendue.**

- [x] Intégration du fa-solid fa-book
- [x] Manque un titre
- [x] 4 actions (voir l'exemple)

Exemple
![Image](https://github.com/user-attachments/assets/a0861b45-7ca5-4189-a595-9835fb09290b)

![Image](https://github.com/user-attachments/assets/b366f91d-9c71-4aed-99dd-331c5602c9b0)

**Comment by eoxia-amandine** [comment]
Proposition design Infobox :
 
![20241002_infobox_v1](https://github.com/user-attachments/assets/9a29a3e7-6710-44d3-90fc-9df7e0edd723)

**Comment by lmag** [comment]
Parfat @eoxia-amandine
