### ISSUE TITLE
Import Arborescence en mode multi compagny

### ISSUE THREAD

**Issue by HoulesBenoit** [Evarisk/Digirisk#4136]
**Vous avez trouvé un BUG ! Bravo !**
"Importation des données globales de Digirisk Dolibarr au format ZIP (Arborescence, risques et signalisations)" ne semble pas fonctionner en mode multi-compagny

**Vous pouvez décrire comment le reproduire ici**
1 - J'ai exporté avec la fonctionnalité "Exportation des données globales de Digirisk Dolibarr au format ZIP (Arborescence, risques et signalisations)" depuis une compagnie.
2 - J'ai importé avec la fonctionnalité "Importation des données globales de Digirisk Dolibarr au format ZIP (Arborescence, risques et signalisations)" sur une seconde compagnie.
3 - J'ai bien le message "fichier téléversé" ==> Mais je n'ai rien dans mon DU (aucun(e) GP et UT).

url pour 1 et 2 : custom/digiriskdolibarr/view/digirisktools.php
url pour 3 : custom/digiriskdolibarr/view/digiriskelement/digiriskelement_organization.php?idmenu=937&mainmenu=digiriskdolibarr&leftmenu=

**Copie d'écran**
On adore les copies d'écran afin de mieux comprendre

**Votre configuration sauf si vous êtes chez evarisk.com**
 - OS: Win11
 - Navigateur Firefox
 - Version 128.3.0esr (64 bits)

Dolibarr : 19.0.2
DigiriskDolibarr 10.2.1

**Comment by HoulesBenoit** [comment]
Quelques logs pour analyser : 
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  file_get_contents(/var/www/documents/6/digiriskdolibarr/temp/20241017095059_dolibarr_global_export.json): Failed to open stream: No such file or directory in /var/www/html/custom/digiriskdolibarr/view/digirisktools.php on line 657","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Trying to access array offset on value of type null in /var/www/html/custom/digiriskdolibarr/view/digirisktools.php on line 660","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Undefined array key "customsql" in /var/www/html/custom/saturne/lib/object.lib.php on line 103","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Trying to access array offset on value of type null in /var/www/html/custom/saturne/lib/object.lib.php on line 103","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"error_log","@app":"digirisk","message":"PHP Warning:  Attempt to read property "element" on null in /var/www/html/custom/digiquali/class/actions_digiquali.class.php on line 203","clientIP":"XX.XXX.XX.XX:PPPP","level":"warn"}
{"@type":"access_log","@app":"digirisk","message":"POST /custom/digiriskdolibarr/view/digirisktools.php HTTP/1.1","statut":"200","temps":"314077","taille":"11446","clientIP":"XX.XXX.XX.XX"}
{"@type":"access_log","@app":"digirisk","message":"GET /custom/multicompany/css/multicompany.css.php?lang=fr_FR&theme=eldy&userid=17&entity=6&layout=classic&version=19.0.2&revision=3 HTTP/1.1","statut":"200","temps":"81226","taille":"2952","clientIP":"XX.XXX.XX.XX"}
{"@type":"access_log","@app":"digirisk","message":"GET /theme/dolibarr_256x256_color.png HTTP/1.1","statut":"200","temps":"239","taille":"3678","clientIP":"XX.XXX.XX.XX"}

J'ai cherché dans le dossier /var/www/documents/6/digiriskdolibarr/temp/ il n'y a rien.
J'ai checké les droits, on a des droits en écriture depuis le dossier www (et l'ensemble des sous-dossiers) pour le user www-data.

Merci d'avance.
Cordialement,

**Comment by lmag** [comment]
Est-ce possible de reproduire le bug sur la demo.digirisk.com ?

**Comment by HoulesBenoit** [comment]
Je viens de rejouer le cas de test ici : https://demodoli.digirisk.com/htdocs/custom/digiriskdolibarr/view/digiriskelement/digiriskelement_organization.php?idmenu=4282&mainmenu=digiriskdolibarr&leftmenu=
avec entite "Entreprise tertiaire"

J'ai repris le fichier initial et j'ai conservé 1 GP et 1 UT seulement. Et là le fichier passe bien.
Donc cela viendrait plutôt du fichier json généré en sorti.

je mets le fichier json généré qui pose souci pour que vous puissiez déterminer ce qui pose souci.
[20241017095058_dolibarr_global_export.json](https://github.com/user-attachments/files/17429537/20241017095058_dolibarr_global_export.json)

**Comment by ribrahime** [comment]
Bonjour,
Je viens de reprendre le problème, le fichier JSON transmis par @HoulesBenoit  contenait une erreur. Cela concerne le format JSON avec une erreur ligne 144 du fichier. Il y a une virgule qui a été placé à la fin de ce fichier.

Nous savons pas exactement le motif de cette erreur peut-être au moment de la génération du fichier ou une mauvaise manipulation à la suite de l'export.

Petite piste d'amélioration de l'interface utilisateur, car même si le fichier importé contient une erreur, nous avons quand même un message nous indiquant que le "Fichier(s) téléversés(s) avec succès" alors que ce n'est pas le cas quand on va regarder sur document unique.
