### ISSUE TITLE
[Amélioration] - Statistique pour les tickets/registres

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#4142]
**Ticket tableau de bord de pilotage et indicateur visuel **

- [x] - Nombre de tickets Ouverts
- [x] - Ticket le plus vieux durée brut (4 j 02:04)
- [x] - Ticket le plus vieux depuis de le dernier échange (4 j 02:04)
- [x] - Nombre de tickets assignés par personne ?
- [x] - Délais moyen de traitement des tickets par Jour, pas mois, par an
- [x] - Délais moyen de traitement des tickets par jour/personne
- [x] -- Complexe en fonction des passages de ticket de personnes en personnes
- [x] - Nombre d'échanges sur un ticket
- [x] - Top 10 des tiers avec le plus de tickets

**Ticket tableau de bord de pilotage individuel**
@todo

**Comment by eoxia-amandine** [comment]
Proposition maquette : 
![Box infos - Tickets](https://github.com/user-attachments/assets/03d43433-c7a4-4102-9e00-195cf1214e0d)
