### ISSUE TITLE
[Amélioration] - IHM amélioration de la lisibilité du bloc actions en cours

### ISSUE THREAD

**Issue by nrenner84** [Evarisk/Digirisk#4198]
Il serait intéressant de mettre le libellé de l'action en première ligne plutôt que la référence afin de facilité la lecture et la communication des actions
![image](https://github.com/user-attachments/assets/8484fc2e-8a22-40e5-a3e1-33050e7f94b1)

**Comment by lmag** [comment]
Merci pour votre premier retour :)
Proposition à poursuivre 
![image](https://github.com/user-attachments/assets/5f892cc0-6be9-46a1-9a5e-328d4bef12cc)

**Comment by lmag** [comment]
@evarisk-charles Séparation des blocs ?
