### ISSUE TITLE
si le participant n'a pas de mail, on ne peut pas l'ajouter au plan de prévention

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/Digirisk#461]
ex : user email vide , on va le modifer , mais la ressource dans digirisksignature n'est plus a jour ducoup

admettons :  
un participant a pas signé, on lui envoie un mail de signature
s'il a pas de signature, on va modifier le contact pour lui rajouter un mail
cependant, le participants dans digirisk_signature_preventionplan n'a pas d'email

--> au moment de renvoyer le mail, si le patrticipant n'en a pas mais que le contact lié (avec le element  id et element type) en a un, proposer d'envoyer à ce mail à la place

**Comment by evarisk-theo** [comment]
proposition : bloquer la création du PP / l'ajout de la ressource si elle a pas d'e-mail ?
