### ISSUE TITLE
[BUG] - Perte de l'ID du risque lors de la modifaction de la tache directement dans Dolibarr

### ISSUE THREAD

**Issue by jf-maigret** [Evarisk/Digirisk#517]
[BUG] - Perte de l'ID du risque lors de la modifaction de la tache directement dans Dolibarr
On ne peut pas remettre l'ID puisque le champs est masqué

**Comment by jf-maigret** [comment]
![image](https://user-images.githubusercontent.com/89776475/131320222-4c124c90-11bf-42d1-bcc7-dfde63ea9cef.png)
Manque le Hook sur la modification

**Comment by evarisk-theo** [comment]
Thank you for your issue, it should be fixed soon

**Comment by evarisk-theo** [comment]
fixed : fc3293d651c0fdbb6f02c297f632c286a7772db6
