### ISSUE TITLE
bravo vous avez signé une fois qu'on a signé sur l'interface publique

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#555]
![image](https://user-images.githubusercontent.com/52404047/132326361-5988acc4-d910-498d-9350-d57941dd2e22.png)
![image](https://user-images.githubusercontent.com/52404047/132326424-84fd41b0-0d09-42c1-83de-cf4ad5be2710.png)
![image](https://user-images.githubusercontent.com/52404047/132326766-2d693daf-ca3a-4af0-8e87-f831295f8592.png)

**Comment by eoxia-amandine** [comment]
![01-signature-1](https://user-images.githubusercontent.com/18576747/132652405-5f0c7b01-1fee-41dd-b33d-aecb787beab8.png)
![01-signature-2](https://user-images.githubusercontent.com/18576747/132652411-09cf492e-adb6-4a76-9a98-7ea1c8ee3334.png)
![01-signature-3](https://user-images.githubusercontent.com/18576747/132652415-4d6be959-14a1-4823-9175-aaf32575ef39.png)

**Comment by eoxia-amandine** [comment]
![02-signature_v2](https://user-images.githubusercontent.com/18576747/132654620-7a452d44-ffa9-4f13-894a-2e1c3932a69a.png)
![03-signature_v2](https://user-images.githubusercontent.com/18576747/132654621-05afaf65-f21f-4b60-aafe-f0e0fc246666.png)
