### ISSUE TITLE
[NEW] Mise en place de la notion de pénibilité par Unité de Travail

### ISSUE THREAD

**Issue by beziade** [Evarisk/Digirisk#59]
Bonjour,
Avez vous pensé à mettre en place la notion de pénibilité par unité de travail :
https://www.inrs.fr/demarche/penibilite/ce-qu-il-faut-retenir.html
https://www.compteprofessionnelprevention.fr/home.html
Bien cordialement

**Comment by lmag** [comment]
Intégration des illustrations et des contrôles pour les personnels de la structure
![image](https://github.com/Evarisk/Digirisk/assets/3288514/a6d6ca73-7fd7-4c8a-9dab-6b2ab2ee31a7)
Génération de la fiche par salariés et par année fiscale de l'entreprise et/ou par année civile
Exemple de fiche 
![image](https://github.com/Evarisk/Digirisk/assets/3288514/a09ce259-ad75-4750-84e5-3c7dfc208f44)

**Comment by lmag** [comment]
Exemple de fiche par salariées reliées au DU
![image](https://github.com/Evarisk/Digirisk/assets/3288514/0320628a-d7c7-4883-832c-bfc0b3abf2f2)

Détails de seuil à controler
![image](https://github.com/Evarisk/Digirisk/assets/3288514/023674aa-06e0-45d4-9da9-ddaa33056ea4)

**Comment by lmag** [comment]
Nous avions dans une ancienne version de DigiRisk mis en place toute la traçabilité de la pénibilité ... Le Challenge étant de le faire sans faire une usine à gaz !
@beziade

**Comment by lmag** [comment]
Doublon je cloture à suivre ici : https://github.com/Evarisk/Digirisk/issues/3992
