### ISSUE TITLE
Perte des données en cas de message d'erreur

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#664]
En cas de manque de données le message d'erreur engendre la perte de la saisi
![image](https://user-images.githubusercontent.com/3288514/133316604-a575e7bd-62be-4f9e-86f7-ccad554f68b3.png)

**Comment by evarisk-theo** [comment]
fixed : eb481019427a3a3c1ef7b2dac1ddd8acf42a8b1b
