### ISSUE TITLE
Nouvelle page de connexion mondoli

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#691]
- [x] ne pas laisser voir les autres entités aux clients
- [x] trouver un moyen pour qu'il se co auto à la bonne entité
- [x] virer version de dolibarr
- [x] virer logo dolibarr
- [ ] une fois connecté, redirection vers digirisk et pas dolibarr
- [x] ajouter captcha
- [x] désactiver les droits multi entity pour les users simples
- [x] virer le bouton besoin d'assistance ou d'aide, ou rediriger vers la doc de digirisk
- [ ] une page un peu comme sur mon.digirisk.com
- [ ] 
- [x] faire des tests sur une instance proto multicompany

**Comment by nicolas-eoxia** [comment]
conf a regarder
MAIN_APPLICATION_TITLE
MAIN_OPTIMIZEFORTEXTBROWSER

MAIN_SECURITY_DISABLEFORGETPASSLINK
MAIN_HELPCENTER_DISABLELINK

//utile pour faire une page perso
		// Select templates dir
		if (!empty($conf->modules_parts['tpl']))	// Using this feature slow down application
		{
			$dirtpls = array_merge($conf->modules_parts['tpl'], array('/core/tpl/'));
			foreach ($dirtpls as $reldir)
			{
				$tmp = dol_buildpath($reldir.'login.tpl.php');
				if (file_exists($tmp)) { $template_dir = preg_replace('/login\.tpl\.php$/', '', $tmp); break; }
			}
		} else {
			$template_dir = DOL_DOCUMENT_ROOT."/core/tpl/";
		}
// Conf a paramétrer
MAIN_SECURITY_ENABLECAPTCHA 1 
DOL_APPLICATION_TITLE
MAIN_HELPCENTER_LINKTOUSE https://wiki.dolibarr.org/index.php?title=Module_Digirisk
