### ISSUE TITLE
probleme css tâches

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#794]
![image](https://user-images.githubusercontent.com/52404047/134522687-a6b39119-5059-4e62-b5df-91263ec59282.png)

**Comment by evarisk-theo** [comment]
![image](https://user-images.githubusercontent.com/68421590/134673638-23644a51-f4b3-4670-be0a-e458ff87da13.png)

**Comment by eoxia-amandine** [comment]
![listing-actions](https://user-images.githubusercontent.com/18576747/135453741-cd2bd8a4-3bd5-4be7-96f6-264c21e80ba8.png)
