### ISSUE TITLE
resize les champs description et évaluation dans listing de risques

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/Digirisk#82]
utlisée dol_trunc

**Comment by eoxia-amandine** [comment]
@evarisk-theo @nicolas-eoxia Est-ce qu'il est possible de modifier la taille des TD ? Je vois qu'il y a écrit en inline "style=width:2%;"

Si c'est possible à modifie :

- Pour la TD évaluation, rajouter **min-width: 400px** et **width: 400px**
![image](https://user-images.githubusercontent.com/18576747/114001476-42cbd580-985c-11eb-844c-6e7dd786a072.png)

- Pour la TD Description, enlever le width de 2% pour qu'elle prenne toute la largeur possible.
