### ISSUE TITLE
Encodage affichage légal PHOTO problème trouvé

### ISSUE THREAD

**Issue by lmag** [Evarisk/Digirisk#839]
Encodage des accents
Sur le réseau S:\commun\Ressources Humaines\Sécurité au travail\DUERP
Ne passe pas
![image](https://user-images.githubusercontent.com/68421590/135243538-71442852-f04a-4dee-9172-19e161824b0f.png)

**Comment by evarisk-theo** [comment]
https://www.dolibarr.org/forum/t/fckeditor-wrong-encoding/15945/6

**Comment by evarisk-theo** [comment]
le problème c'est wysiwyg
